inherit_gem:
    google-style: google-style.yml

Layout/LineLength:
    Exclude:
        - "acceptance/*.rb"
Lint/ShadowingOuterLocalVariable:
    Enabled: false
Metrics/AbcSize:
    Enabled: false
Metrics/BlockLength: 
    Enabled: false
Metrics/CyclomaticComplexity:
    Enabled: false
Metrics/MethodLength:
    Enabled: false
Style/IfUnlessModifier:
    Enabled: false
Style/Next:
    Enabled: false
