AllCops:
  Exclude:
    - "benchmark/**/*"
    - "google-cloud-firestore.gemspec"
    - "lib/google/firestore/v1beta1/**/*"
    - "lib/google/cloud/firestore/v1beta1/**/*"
    - "lib/google/cloud/firestore/v1beta1.rb"
    - "support/**/*"
    - "Rakefile"
    - "acceptance/**/*"
    - "conformance/*"
    - "test/**/*"
  TargetRubyVersion: 2.2

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/RescueModifier:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/PerceivedComplexity:
  Max: 15
Metrics/AbcSize:
  Max: 30
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Max: 25
Metrics/ParameterLists:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLines: # for the extra line between copyright and code
  Enabled: false
Naming/FileName:
  Exclude:
    - "lib/google-cloud-firestore.rb"
Style/RescueStandardError:
  Exclude:
  - "lib/google/cloud/firestore/client.rb"
Naming/UncommunicativeMethodParamName:
  Enabled: false
