inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "benchmark/**/*"
    - "google-cloud-firestore.gemspec"
    - "support/**/*"
    - "Rakefile"
    - "acceptance/**/*"
    - "conformance/**/*"
    - "test/**/*"

Style/Documentation:
  Enabled: false
Style/GlobalVars:
  Exclude:
    - "samples/acceptance/helper.rb"

Metrics/AbcSize:
  Exclude:
    - "lib/google/cloud/firestore/query.rb"
Metrics/BlockLength:
  Exclude:
    - ".toys.rb"
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 17
Metrics/MethodLength:
  Max: 32
Metrics/PerceivedComplexity:
  Max: 17
Naming/FileName:
  Exclude:
    - "lib/google-cloud-firestore.rb"
