source "https://rubygems.org"

gemspec

gem "google-cloud-core", path: "../google-cloud-core"
gem "google-cloud-env", path: "../google-cloud-env"
gem "google-cloud-errors", path: "../google-cloud-errors"
gem "google-cloud-firestore-admin-v1", path: "../google-cloud-firestore-admin-v1"
gem "google-cloud-firestore-v1", path: "../google-cloud-firestore-v1"

gem "rake"

gem "stackprof" unless Gem.win_platform?
