# Copyright 2017 Google LLC
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require "bundler/setup"
require "bundler/gem_tasks"

require "rubocop/rake_task"
RuboCop::RakeTask.new

require "rake/testtask"
desc "Run tests."
Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList["test/**/*_test.rb"]
  t.warning = false
end

namespace :test do
  desc "Runs tests with coverage."
  task :coverage do
    require "simplecov"
    SimpleCov.start do
      command_name "google-cloud-firestore"
      track_files "lib/**/*.rb"
      add_filter "test/"
    end

    Rake::Task[:test].invoke
  end

  desc "Run conformance tests separately from other unit tests."
  Rake::TestTask.new :conformance do |t|
    t.libs << "test"
    t.test_files = ["test/google/cloud/firestore/conformance_test.rb"]
    t.warning = false
  end
end

# Acceptance tests
desc "Run the firestore acceptance tests."
task :acceptance, :project, :keyfile do |t, args|
  project = args[:project]
  project ||= ENV["FIRESTORE_TEST_PROJECT"] || ENV["GCLOUD_TEST_PROJECT"]
  keyfile = args[:keyfile]
  keyfile ||= ENV["FIRESTORE_TEST_KEYFILE"] || ENV["FIRESTORE_TEST_KEYFILE_JSON"] ||
              ENV["GCLOUD_TEST_KEYFILE"] || ENV["GCLOUD_TEST_KEYFILE_JSON"]
  keyfile = File.read keyfile if keyfile && !keyfile.strip.start_with?("{")
  if project.nil? || keyfile.nil?
    fail "You must provide a project and keyfile. e.g. rake acceptance[test123, /path/to/keyfile.json] or FIRESTORE_TEST_PROJECT=test123 FIRESTORE_TEST_KEYFILE=/path/to/keyfile.json rake acceptance"
  end
  # clear any env var already set
  require "google/cloud/firestore/credentials"
  Google::Cloud::Firestore::Credentials.env_vars.each do |path|
    ENV[path] = nil
  end
  # always overwrite when running tests
  ENV["FIRESTORE_PROJECT"] = project
  ENV["FIRESTORE_KEYFILE_JSON"] = keyfile

  Rake::Task["acceptance:run"].invoke
end

namespace :acceptance do
  desc "Run acceptance tests with coverage."
  task :coverage, :project, :keyfile do |t, args|
    require "simplecov"
    SimpleCov.start do
      command_name "google-cloud-firestore"
      track_files "lib/**/*.rb"
      add_filter "acceptance/"
    end

    Rake::Task[:acceptance].invoke
  end

  desc "Run acceptance cleanup."
  task :cleanup, :project, :keyfile do |t, args|
    project = args[:project]
    project ||= ENV["FIRESTORE_TEST_PROJECT"] || ENV["GCLOUD_TEST_PROJECT"]
    keyfile = args[:keyfile]
    keyfile ||= ENV["FIRESTORE_TEST_KEYFILE"] || ENV["FIRESTORE_TEST_KEYFILE_JSON"] ||
                ENV["GCLOUD_TEST_KEYFILE"] || ENV["GCLOUD_TEST_KEYFILE_JSON"]
    keyfile = File.read keyfile if keyfile && !keyfile.strip.start_with?("{")
    if project.nil? || keyfile.nil?
      fail "You must provide a project and keyfile. e.g. rake acceptance[test123, /path/to/keyfile.json] or FIRESTORE_TEST_PROJECT=test123 FIRESTORE_TEST_KEYFILE=/path/to/keyfile.json rake acceptance"
    end
    # clear any env var already set
    require "google/cloud/firestore/credentials"
    Google::Cloud::Firestore::Credentials.env_vars.each do |path|
      ENV[path] = nil
    end
    # always overwrite when running tests
    ENV["FIRESTORE_PROJECT"] = project
    ENV["FIRESTORE_KEYFILE_JSON"] = keyfile

    $LOAD_PATH.unshift "lib"
    require "google/cloud/firestore"
    puts "Cleaning up Firestore documents and collections."

    firestore = Google::Cloud::Firestore.new
    firestore.cols.each do |col|
      begin
        col.select(firestore.document_id).all_descendants.run.each_slice(500).with_index do |slice, index|
          firestore.batch do |b|
            slice.each do |doc|
              b.delete doc
            end
          end
          puts "Deleted batch #{index+1} of #{slice.count} documents"
        end
      rescue => e
        puts "Error while cleaning up #{col} documents.\n\n#{e}"
      end
    end
  end

  Rake::TestTask.new :run do |t|
    t.libs << "acceptance"
    t.test_files = FileList["acceptance/**/*_test.rb"]
    t.warning = false
  end
end

task :samples do
  Rake::Task["samples:latest"].invoke
end

namespace :samples do
  task :latest do
    if File.directory? "samples"
      Dir.chdir "samples" do
        Bundler.with_unbundled_env do
          ENV["GOOGLE_CLOUD_SAMPLES_TEST"] = "not_master"
          sh "bundle update"
          sh "bundle exec rake test"
        end
      end
    else
      puts "The google-cloud-firestore gem has no samples to test."
    end
  end

  task :master do
    if File.directory? "samples"
      Dir.chdir "samples" do
        Bundler.with_unbundled_env do
          ENV["GOOGLE_CLOUD_SAMPLES_TEST"] = "master"
          sh "bundle update"
          sh "bundle exec rake test"
        end
      end
    else
      puts "The google-cloud-firestore gem has no samples to test."
    end
  end
end

desc "Start an interactive shell."
task :console do
  require "irb"
  require "irb/completion"
  require "pp"

  $LOAD_PATH.unshift "lib"

  require "google-cloud-firestore"
  def gcloud; @gcloud ||= Google::Cloud.new; end

  ARGV.clear
  IRB.start
end

require "yard"
require "yard/rake/yardoc_task"
YARD::Rake::YardocTask.new do |y|
  # y.options << "--fail-on-warning"
end

desc "Run yard-doctest example tests."
task :doctest do
  sh "bundle exec yard config load_plugins true && bundle exec yard doctest"
end

desc "Run the CI build"
task :ci do
  header "BUILDING google-cloud-firestore"
  header "google-cloud-firestore rubocop", "*"
  Rake::Task[:rubocop].invoke
  header "google-cloud-firestore yard", "*"
  header "firestore yard still had warnings", "!"
  Rake::Task[:yard].invoke
  header "google-cloud-firestore doctest", "*"
  Rake::Task[:doctest].invoke
  header "google-cloud-firestore test", "*"
  Rake::Task[:test].invoke
end


namespace :ci do
  desc "Run the CI build, with acceptance tests."
  task :acceptance do
    Rake::Task[:ci].invoke
    header "google-cloud-firestore acceptance", "*"
    Rake::Task[:acceptance].invoke
  end
  task :a do
    # This is a handy shortcut to save typing
    Rake::Task["ci:acceptance"].invoke
  end
end

task :default => :test

def header str, token = "#"
  line_length = str.length + 8
  puts ""
  puts token * line_length
  puts "#{token * 3} #{str} #{token * 3}"
  puts token * line_length
  puts ""
end
