# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source "https://rubygems.org"

master = ENV["GOOGLE_CLOUD_SAMPLES_TEST"] == "master"

gem "google-cloud-video_intelligence", path: master ? "../../google-cloud-video_intelligence" : nil
gem "google-cloud-video_intelligence-v1", path: master ? "../../google-cloud-video_intelligence-v1" : nil
gem "google-cloud-video_intelligence-v1p1beta1", path: master ? "../../google-cloud-video_intelligence-v1p1beta1" : nil
gem "google-cloud-video_intelligence-v1p2beta1", path: master ? "../../google-cloud-video_intelligence-v1p2beta1" : nil

group :test do
  gem "google-cloud-storage"
  gem "minitest", "~> 5.14"
  gem "minitest-focus", "~> 1.1"
  gem "minitest-hooks", "~>1.5"
  gem "rake", ">= 12.0"
  gem "pry"
end
