# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: google/api/cloudquotas/v1beta/quota_adjuster_settings.proto for package 'Google.Cloud.CloudQuotas.V1beta'
# Original file comments:
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'grpc'
require 'google/api/cloudquotas/v1beta/quota_adjuster_settings_pb'

module Google
  module Cloud
    module CloudQuotas
      module V1beta
        module QuotaAdjusterSettingsManager
          # The Quotas Adjuster Settings API is an infrastructure service for Google
          #  Cloud that lets service consumers view and update their quota adjuster
          #  settings.
          #
          # - Update quota adjuster settings.
          # - Get the name of the configurations.
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'google.api.cloudquotas.v1beta.QuotaAdjusterSettingsManager'

            # RPC Method for updating QuotaAdjusterSettings based on the request
            rpc :UpdateQuotaAdjusterSettings, ::Google::Cloud::CloudQuotas::V1beta::UpdateQuotaAdjusterSettingsRequest, ::Google::Cloud::CloudQuotas::V1beta::QuotaAdjusterSettings
            # RPC Method for getting QuotaAdjusterSettings based on the request
            rpc :GetQuotaAdjusterSettings, ::Google::Cloud::CloudQuotas::V1beta::GetQuotaAdjusterSettingsRequest, ::Google::Cloud::CloudQuotas::V1beta::QuotaAdjusterSettings
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
