source "https://rubygems.org"

gemspec

gem "gapic-common", github: "googleapis/gapic-generator-ruby"
gem "google-cloud-core", path: "../google-cloud-core"
gem "google-cloud-env", path: "../google-cloud-env"
gem "google-cloud-errors", path: "../google-cloud-errors"
gem "google-cloud-secretmanager-v1beta1", path: "../google-cloud-secretmanager-v1beta1"

gem "rake", "~> 12.3"

# Pin minitest to 5.11.x to avoid warnings emitted by 5.12.
# See https://github.com/googleapis/google-cloud-ruby/issues/4110
gem "minitest", "~> 5.11.3"
