source "https://rubygems.org"

gemspec

gem "google-cloud-core", path: "../google-cloud-core"
gem "google-cloud-error_reporting", path: "../google-cloud-error_reporting"
gem "google-cloud-errors", path: "../google-cloud-errors"
gem "google-cloud-logging", path: "../google-cloud-logging"
gem "google-cloud-trace", path: "../google-cloud-trace"
gem "stackdriver-core", path: "../stackdriver-core"

gem "rake"
