# Copyright 2016 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


require "bundler/setup"
require "bundler/gem_tasks"

require "rubocop/rake_task"
RuboCop::RakeTask.new

desc "Run tests."
task :test do
  $LOAD_PATH.unshift "lib", "test"
  Dir.glob("test/**/*_test.rb").each { |file| require_relative file }
end

namespace :test do
  desc "Run tests with coverage."
  task :coverage do
    require "simplecov"
    SimpleCov.start do
      command_name "stackdriver"
      track_files "lib/**/*.rb"
      add_filter "test/"
    end

    Rake::Task[:test].invoke
  end
end

desc "Run acceptance tests."
task :acceptance do
  puts "The stackdriver gem does not have acceptance tests."
end

namespace :acceptance do
  task :run do
    puts "This gem does not have acceptance tests."
  end

  desc "Run acceptance cleanup."
  task :cleanup do
  end
end

desc "Run yard-doctest example tests."
task :doctest do
  puts "The stackdriver gem does not have doctest tests."
end

desc "Start an interactive shell."
task :console do
  require "irb"
  require "irb/completion"
  require "pp"

  $LOAD_PATH.unshift "lib"

  require "google/cloud"
  Bundler.require # load all the gems defined in the Gemfile
  def gcloud
    @gcloud ||= Google::Cloud.new
  end

  ARGV.clear
  IRB.start
end

require "yard"
require "yard/rake/yardoc_task"
YARD::Rake::YardocTask.new do |y|
  y.options << "--fail-on-warning"
end

desc "Run the CI build"
task :ci do
  header "BUILDING stackdriver"
  Rake::Task[:debugger_c].invoke
  header "stackdriver rubocop", "*"
  Rake::Task[:rubocop].invoke
  header "stackdriver yard", "*"
  Rake::Task[:yard].invoke
  header "stackdriver doctest", "*"
  Rake::Task[:doctest].invoke
  header "stackdriver test", "*"
  Rake::Task[:test].invoke
end
namespace :ci do
  desc "Run the CI build, with acceptance tests."
  task :acceptance do
    Rake::Task[:ci].invoke
    header "stackdriver acceptance", "*"
    Rake::Task[:acceptance].invoke
  end
  task :a do
    # This is a handy shortcut to save typing
    Rake::Task["ci:acceptance"].invoke
  end
end

task default: :test

desc "Compiles c extension for google-cloud-debugger"
task :debugger_c do
  header "compiling google-cloud-debugger", "*"
  debugger_directory = File.join(File.dirname(Dir.getwd), "google-cloud-debugger")
  Dir.chdir(debugger_directory) do
    Bundler.with_clean_env do
      sh "bundle update"
      sh "bundle exec rake compile"
    end
  end
end

def header str, token = "#"
  line_length = str.length + 8
  puts ""
  puts token * line_length
  puts "#{token * 3} #{str} #{token * 3}"
  puts token * line_length
  puts ""
end
