# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# TODO: Updated with GEM after alpha release
github "googleapis/google-cloud-ruby" do
  gem "google-cloud-bigtable"
end

gem "commander", "~> 4.4", ">= 4.4.5"
