source 'https://rubygems.org'

# eval_gemfile File.join(File.dirname(__FILE__), "../../Gemfile")

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.0', '>= 5.2.6'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use Puma as the app server
gem 'puma', '>= 5.0', '< 7'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console'
  gem 'listen', '>= 3.7.0', '< 3.9.1'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem "google-cloud-bigquery", path: "../../google-cloud-bigquery"
gem "google-cloud-core", path: "../../google-cloud-core"
gem "google-cloud-debugger", path: "../../google-cloud-debugger"
gem "google-cloud-datastore", path: "../../google-cloud-datastore"
gem "google-cloud-debugger", path: "../../google-cloud-debugger"
gem "google-cloud-dns", path: "../../google-cloud-dns"
gem "google-cloud-error_reporting", path: "../../google-cloud-error_reporting"
gem "google-cloud-language", path: "../../google-cloud-language"
gem "google-cloud-logging", path: "../../google-cloud-logging"
gem "google-cloud-monitoring", path: "../../google-cloud-monitoring"
gem "google-cloud-pubsub", path: "../../google-cloud-pubsub"
gem "google-cloud-resource_manager", path: "../../google-cloud-resource_manager"
gem "google-cloud-speech", path: "../../google-cloud-speech"
gem "google-cloud-storage", path: "../../google-cloud-storage"
gem "google-cloud-trace", path: "../../google-cloud-trace"
gem "google-cloud-translate", path: "../../google-cloud-translate"
gem "google-cloud-vision", path: "../../google-cloud-vision"
gem "google-cloud", path: "../../google-cloud"
gem "gcloud", path: "../../gcloud"
gem "stackdriver", path: "../../stackdriver", require: false
gem "stackdriver-core", path: "../../stackdriver-core"
