# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source "https://rubygems.org"

if ENV["GOOGLE_CLOUD_SAMPLES_TEST"] == "master"
  gem "google-cloud-talent", path: "../../google-cloud-talent"
  gem "google-cloud-talent-v4beta1", path: "../../google-cloud-talent-v4beta1"
else
  # rubocop:disable Bundler/DuplicatedGem
  gem "google-cloud-talent"
  # rubocop:enable Bundler/DuplicatedGem
end

group :test do
  gem "google-style", "~> 1.24.0"
  gem "minitest", "~> 5.14"
  gem "rake"
end
