assign_issues_by:
  - labels:
    - 'api: storage'
    to:
    - bajajneha27
  - labels:
    - 'api: secretmanager'
    to:
    - GoogleCloudPlatform/cloud-secrets-team
  - labels:
    - 'api: parametermanager'
    to:
    - GoogleCloudPlatform/cloud-parameters-team

assign_issues:
 - dazuma
 - aandreassa
