source "https://rubygems.org"

gemspec
gem "gapic-common", path: "../gapic-common/"

gem "google-cloud-artifact_registry-v1", path: "../google-cloud-artifact_registry-v1"
gem "google-cloud-artifact_registry-v1beta2", path: "../google-cloud-artifact_registry-v1beta2"
