source "https://rubygems.org"

gem "rake"
gem "minitest", "~> 5.9"
gem "minitest-autotest", "~> 1.0"
gem "minitest-focus", "~> 1.1"
gem "minitest-rg", "~> 5.2"
gem "autotest-suffix", "~> 1.1"
gem "rubocop", "<= 0.35.1"
gem "simplecov", "~> 0.9"
gem "coveralls", "~> 0.7"
gem "yard", "~> 0.9"
gem "yard-doctest", "~> 0.1.8"
gem "gems", "~> 0.8"
gem "actionpack", ">= 4.0"
gem "railties", ">= 4.0"
gem "rack", ">= 0.1"
gem "sinatra", "~> 1.4"

gem "google-cloud-core", path: "google-cloud-core"
gem "google-cloud-bigquery", path: "google-cloud-bigquery"
gem "google-cloud-datastore", path: "google-cloud-datastore"
gem "google-cloud-dns", path: "google-cloud-dns"
gem "google-cloud-error_reporting", path: "google-cloud-error_reporting"
gem "google-cloud-language", path: "google-cloud-language"
gem "google-cloud-logging", path: "google-cloud-logging"
gem "google-cloud-monitoring", path: "google-cloud-monitoring"
gem "google-cloud-pubsub", path: "google-cloud-pubsub"
gem "google-cloud-resource_manager", path: "google-cloud-resource_manager"
gem "google-cloud-speech", path: "google-cloud-speech"
gem "google-cloud-storage", path: "google-cloud-storage"
gem "google-cloud-translate", path: "google-cloud-translate"
gem "google-cloud-vision", path: "google-cloud-vision"
gem "google-cloud", path: "google-cloud"
gem "gcloud", path: "gcloud"
gem "stackdriver", path: "stackdriver"
