source "https://rubygems.org"

gemspec

gem "google-cloud-text_to_speech-v1", path: "../google-cloud-text_to_speech-v1"
gem "google-cloud-text_to_speech-v1beta1", path: "../google-cloud-text_to_speech-v1beta1"
