source "https://rubygems.org"

gemspec

gem "rake", "~> 11.0"
gem "google-api-client", "~> 0.13.0"
gem "google-gax", "~> 0.8.0"
gem "google-cloud-env", path: "../google-cloud-env"
gem "gcloud-jsondoc",
    git: "https://github.com/GoogleCloudPlatform/google-cloud-ruby.git",
    branch: "gcloud-jsondoc"

# WORKAROUND: builds are having problems since the release of 3.0.0
# pin to the last known good version
gem "public_suffix", "~> 2.0"

# TEMP: rainbow (a dependency of rubocop) version 2.2 seems to have a problem,
# so pinning to 2.1 for now.
gem "rainbow", "~> 2.1.0"
