source "https://rubygems.org"

gemspec

gem "google-cloud-tasks-v2", path: "../google-cloud-tasks-v2"
gem "google-cloud-tasks-v2beta2", path: "../google-cloud-tasks-v2beta2"
gem "google-cloud-tasks-v2beta3", path: "../google-cloud-tasks-v2beta3"
