# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/artifactregistry/v1beta2/version.proto

require 'google/api/annotations_pb'
require 'google/api/field_behavior_pb'
require 'google/api/resource_pb'
require 'google/devtools/artifactregistry/v1beta2/tag_pb'
require 'google/protobuf/struct_pb'
require 'google/protobuf/timestamp_pb'
require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/devtools/artifactregistry/v1beta2/version.proto", :syntax => :proto3) do
    add_message "google.devtools.artifactregistry.v1beta2.Version" do
      optional :name, :string, 1
      optional :description, :string, 3
      optional :create_time, :message, 5, "google.protobuf.Timestamp"
      optional :update_time, :message, 6, "google.protobuf.Timestamp"
      repeated :related_tags, :message, 7, "google.devtools.artifactregistry.v1beta2.Tag"
      optional :metadata, :message, 8, "google.protobuf.Struct"
    end
    add_message "google.devtools.artifactregistry.v1beta2.ListVersionsRequest" do
      optional :parent, :string, 1
      optional :page_size, :int32, 2
      optional :page_token, :string, 3
      optional :view, :enum, 4, "google.devtools.artifactregistry.v1beta2.VersionView"
      optional :order_by, :string, 5
    end
    add_message "google.devtools.artifactregistry.v1beta2.ListVersionsResponse" do
      repeated :versions, :message, 1, "google.devtools.artifactregistry.v1beta2.Version"
      optional :next_page_token, :string, 2
    end
    add_message "google.devtools.artifactregistry.v1beta2.GetVersionRequest" do
      optional :name, :string, 1
      optional :view, :enum, 2, "google.devtools.artifactregistry.v1beta2.VersionView"
    end
    add_message "google.devtools.artifactregistry.v1beta2.DeleteVersionRequest" do
      optional :name, :string, 1
      optional :force, :bool, 2
    end
    add_enum "google.devtools.artifactregistry.v1beta2.VersionView" do
      value :VERSION_VIEW_UNSPECIFIED, 0
      value :BASIC, 1
      value :FULL, 2
    end
  end
end

module Google
  module Cloud
    module ArtifactRegistry
      module V1beta2
        Version = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.devtools.artifactregistry.v1beta2.Version").msgclass
        ListVersionsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.devtools.artifactregistry.v1beta2.ListVersionsRequest").msgclass
        ListVersionsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.devtools.artifactregistry.v1beta2.ListVersionsResponse").msgclass
        GetVersionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.devtools.artifactregistry.v1beta2.GetVersionRequest").msgclass
        DeleteVersionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.devtools.artifactregistry.v1beta2.DeleteVersionRequest").msgclass
        VersionView = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.devtools.artifactregistry.v1beta2.VersionView").enummodule
      end
    end
  end
end
