source "https://rubygems.org"

gemspec

local_dependencies = [
  "google-cloud-trace-v1",
  "google-cloud-trace-v2",
  "google-cloud-core",
  "google-cloud-errors",
  "stackdriver-core"
]

main_spec = gemspecs.last || Bundler.load_gemspec(File.join(__dir__, "google-cloud-trace.gemspec"))
local_dependencies.each do |name|
  spec_path = File.expand_path "../#{name}/#{name}.gemspec", __dir__
  unless File.file? spec_path
    warn "WARNING: Disabled local dependency for #{name} because gemspec not found."
    next
  end
  version = Bundler.load_gemspec(spec_path).version
  if main_spec.dependencies.any? { |dep| dep.name == name && !dep.requirement.satisfied_by?(version) }
    warn "WARNING: Disabled local dependency for #{name} because the gemspec disallows version #{version}."
    next
  end
  gem name, path: "../#{name}"
end

gem "activerecord", ">= 5.0", "< 8.1.4"
gem "autotest-suffix", "~> 1.1"
gem "benchmark", "~> 0.5.0"
gem "cgi", "~> 0.5.0"
gem "faraday", ">= 1.3", "< 3"
gem "google-style", "~> 1.32.0"
gem "irb", "~> 1.17"
gem "minitest", "~> 6.0.2"
gem "minitest-autotest", "~> 1.0"
gem "minitest-focus", "~> 1.4"
gem "minitest-mock", "~> 5.27"
gem "minitest-rg", "~> 5.3"
gem "ostruct", "~> 0.5.5"
gem "railties", ">= 5.0", "< 8.1.4"
gem "rake"
gem "redcarpet", "~> 3.6"
gem "simplecov", "~> 0.22"
gem "yard", "~> 0.9"
gem "yard-doctest" # , "~> 0.1.6"
