source "https://rubygems.org"

gemspec

gem "rake", "~> 11.0"
gem "stackdriver-core", path: "../stackdriver-core"
gem "gcloud-jsondoc",
    git: "https://github.com/GoogleCloudPlatform/google-cloud-ruby.git",
    branch: "gcloud-jsondoc"
