# frozen_string_literal: true

# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Cloud
    module VectorSearch
      module V1
        # Message describing Collection object
        # @!attribute [rw] name
        #   @return [::String]
        #     Identifier. name of resource
        # @!attribute [rw] display_name
        #   @return [::String]
        #     Optional. User-specified display name of the collection
        # @!attribute [rw] description
        #   @return [::String]
        #     Optional. User-specified description of the collection
        # @!attribute [r] create_time
        #   @return [::Google::Protobuf::Timestamp]
        #     Output only. [Output only] Create time stamp
        # @!attribute [r] update_time
        #   @return [::Google::Protobuf::Timestamp]
        #     Output only. [Output only] Update time stamp
        # @!attribute [rw] labels
        #   @return [::Google::Protobuf::Map{::String => ::String}]
        #     Optional. Labels as key value pairs.
        # @!attribute [rw] vector_schema
        #   @return [::Google::Protobuf::Map{::String => ::Google::Cloud::VectorSearch::V1::VectorField}]
        #     Optional. Schema for vector fields. Only vector fields in this schema will
        #     be searchable. Field names must contain only alphanumeric characters,
        #     underscores, and hyphens.
        # @!attribute [rw] data_schema
        #   @return [::Google::Protobuf::Struct]
        #     Optional. JSON Schema for data.
        #     Field names must contain only alphanumeric characters,
        #     underscores, and hyphens.
        #     The schema must be compliant with
        #     [JSON Schema Draft 7](https://json-schema.org/draft-07/schema).
        # @!attribute [rw] encryption_spec
        #   @return [::Google::Cloud::VectorSearch::V1::EncryptionSpec]
        #     Optional. Immutable. Specifies the customer-managed encryption key spec for
        #     a Collection. If set, this Collection and all sub-resources of this
        #     Collection will be secured by this key.
        class Collection
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods

          # @!attribute [rw] key
          #   @return [::String]
          # @!attribute [rw] value
          #   @return [::String]
          class LabelsEntry
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # @!attribute [rw] key
          #   @return [::String]
          # @!attribute [rw] value
          #   @return [::Google::Cloud::VectorSearch::V1::VectorField]
          class VectorSchemaEntry
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end
        end

        # Message describing a vector field.
        # @!attribute [rw] dense_vector
        #   @return [::Google::Cloud::VectorSearch::V1::DenseVectorField]
        #     Dense vector field.
        #
        #     Note: The following fields are mutually exclusive: `dense_vector`, `sparse_vector`. If a field in that set is populated, all other fields in the set will automatically be cleared.
        # @!attribute [rw] sparse_vector
        #   @return [::Google::Cloud::VectorSearch::V1::SparseVectorField]
        #     Sparse vector field.
        #
        #     Note: The following fields are mutually exclusive: `sparse_vector`, `dense_vector`. If a field in that set is populated, all other fields in the set will automatically be cleared.
        class VectorField
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Message describing a dense vector field.
        # @!attribute [rw] dimensions
        #   @return [::Integer]
        #     Dimensionality of the vector field.
        # @!attribute [rw] vertex_embedding_config
        #   @return [::Google::Cloud::VectorSearch::V1::VertexEmbeddingConfig]
        #     Optional. Configuration for generating embeddings for the vector field. If
        #     not specified, the embedding field must be populated in the DataObject.
        class DenseVectorField
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Message describing a sparse vector field.
        class SparseVectorField
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Message for requesting list of Collections
        # @!attribute [rw] parent
        #   @return [::String]
        #     Required. Parent value for ListCollectionsRequest
        # @!attribute [rw] page_size
        #   @return [::Integer]
        #     Optional. Requested page size. Server may return fewer items than
        #     requested. If unspecified, server will pick an appropriate default.
        # @!attribute [rw] page_token
        #   @return [::String]
        #     Optional. A token identifying a page of results the server should return.
        # @!attribute [rw] filter
        #   @return [::String]
        #     Optional. Filtering results
        # @!attribute [rw] order_by
        #   @return [::String]
        #     Optional. Hint for how to order the results
        class ListCollectionsRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Message for response to listing Collections
        # @!attribute [rw] collections
        #   @return [::Array<::Google::Cloud::VectorSearch::V1::Collection>]
        #     The list of Collection
        # @!attribute [rw] next_page_token
        #   @return [::String]
        #     A token identifying a page of results the server should return.
        # @!attribute [rw] unreachable
        #   @return [::Array<::String>]
        #     Unordered list. Locations that could not be reached.
        class ListCollectionsResponse
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Message for getting a Collection
        # @!attribute [rw] name
        #   @return [::String]
        #     Required. Name of the resource
        class GetCollectionRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Message for creating a Collection
        # @!attribute [rw] parent
        #   @return [::String]
        #     Required. Value for parent.
        # @!attribute [rw] collection_id
        #   @return [::String]
        #     Required. ID of the Collection to create.
        #     The id must be 1-63 characters long, and comply with
        #     [RFC1035](https://www.ietf.org/rfc/rfc1035.txt).
        #     Specifically, it must be 1-63 characters long and match the regular
        #     expression `[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?`.
        # @!attribute [rw] collection
        #   @return [::Google::Cloud::VectorSearch::V1::Collection]
        #     Required. The resource being created
        # @!attribute [rw] request_id
        #   @return [::String]
        #     Optional. An optional request ID to identify requests. Specify a unique
        #     request ID so that if you must retry your request, the server will know to
        #     ignore the request if it has already been completed. The server will
        #     guarantee that for at least 60 minutes since the first request.
        #
        #     For example, consider a situation where you make an initial request and the
        #     request times out. If you make the request again with the same request
        #     ID, the server can check if original operation with the same request ID
        #     was received, and if so, will ignore the second request. This prevents
        #     clients from accidentally creating duplicate commitments.
        #
        #     The request ID must be a valid UUID with the exception that zero UUID is
        #     not supported (00000000-0000-0000-0000-000000000000).
        class CreateCollectionRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Message for updating a Collection
        # @!attribute [rw] update_mask
        #   @return [::Google::Protobuf::FieldMask]
        #     Optional. Field mask is used to specify the fields to be overwritten in the
        #     Collection resource by the update.
        #     The fields specified in the update_mask are relative to the resource, not
        #     the full request. A field will be overwritten if it is in the mask. If the
        #     user does not provide a mask then all fields present in the request will be
        #     overwritten.
        #
        #     The following fields support update: `display_name`, `description`,
        #     `labels`, `data_schema`, `vector_schema`.
        #     For `data_schema` and `vector_schema`, fields can only be added, not
        #     deleted, but `vertex_embedding_config` in `vector_schema` can be added or
        #     removed.
        #     Partial updates for `data_schema` and `vector_schema` are also supported
        #     by using sub-field paths in `update_mask`, e.g.
        #     `data_schema.properties.foo` or `vector_schema.my_vector_field`.
        #
        #     If `*` is provided in the update_mask, full replacement will be performed.
        # @!attribute [rw] collection
        #   @return [::Google::Cloud::VectorSearch::V1::Collection]
        #     Required. The resource being updated
        # @!attribute [rw] request_id
        #   @return [::String]
        #     Optional. An optional request ID to identify requests. Specify a unique
        #     request ID so that if you must retry your request, the server will know to
        #     ignore the request if it has already been completed. The server will
        #     guarantee that for at least 60 minutes since the first request.
        #
        #     For example, consider a situation where you make an initial request and the
        #     request times out. If you make the request again with the same request
        #     ID, the server can check if original operation with the same request ID
        #     was received, and if so, will ignore the second request. This prevents
        #     clients from accidentally creating duplicate commitments.
        #
        #     The request ID must be a valid UUID with the exception that zero UUID is
        #     not supported (00000000-0000-0000-0000-000000000000).
        class UpdateCollectionRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Message for deleting a Collection
        # @!attribute [rw] name
        #   @return [::String]
        #     Required. Name of the resource
        # @!attribute [rw] request_id
        #   @return [::String]
        #     Optional. An optional request ID to identify requests. Specify a unique
        #     request ID so that if you must retry your request, the server will know to
        #     ignore the request if it has already been completed. The server will
        #     guarantee that for at least 60 minutes after the first request.
        #
        #     For example, consider a situation where you make an initial request and the
        #     request times out. If you make the request again with the same request
        #     ID, the server can check if original operation with the same request ID
        #     was received, and if so, will ignore the second request. This prevents
        #     clients from accidentally creating duplicate commitments.
        #
        #     The request ID must be a valid UUID with the exception that zero UUID is
        #     not supported (00000000-0000-0000-0000-000000000000).
        # @!attribute [rw] force
        #   @return [::Boolean]
        #     Optional. If set to true, any Indexes and DataObjects from this Collection
        #     will also be deleted. (Otherwise, the request will only work if the
        #     Collection has no Indexes and DataObjects.)
        class DeleteCollectionRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Message describing Index object
        # @!attribute [rw] dedicated_infrastructure
        #   @return [::Google::Cloud::VectorSearch::V1::DedicatedInfrastructure]
        #     Optional. Dedicated infrastructure for the index.
        # @!attribute [rw] dense_scann
        #   @return [::Google::Cloud::VectorSearch::V1::DenseScannIndex]
        #     Optional. Dense ScaNN index.
        # @!attribute [rw] name
        #   @return [::String]
        #     Identifier. name of resource
        # @!attribute [rw] display_name
        #   @return [::String]
        #     Optional. User-specified display name of the index
        # @!attribute [rw] description
        #   @return [::String]
        #     Optional. User-specified description of the index
        # @!attribute [rw] labels
        #   @return [::Google::Protobuf::Map{::String => ::String}]
        #     Optional. Labels as key value pairs.
        # @!attribute [r] create_time
        #   @return [::Google::Protobuf::Timestamp]
        #     Output only. [Output only] Create time stamp
        # @!attribute [r] update_time
        #   @return [::Google::Protobuf::Timestamp]
        #     Output only. [Output only] Update time stamp
        # @!attribute [rw] distance_metric
        #   @return [::Google::Cloud::VectorSearch::V1::DistanceMetric]
        #     Optional. Distance metric used for indexing. If not specified, will default
        #     to DOT_PRODUCT.
        # @!attribute [rw] index_field
        #   @return [::String]
        #     Required. The collection schema field to index.
        # @!attribute [rw] filter_fields
        #   @return [::Array<::String>]
        #     Optional. The fields to push into the index to enable fast ANN inline
        #     filtering.
        # @!attribute [rw] store_fields
        #   @return [::Array<::String>]
        #     Optional. The fields to push into the index to enable inline data
        #     retrieval.
        class Index
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods

          # @!attribute [rw] key
          #   @return [::String]
          # @!attribute [rw] value
          #   @return [::String]
          class LabelsEntry
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end
        end

        # Message for creating an Index.
        # @!attribute [rw] parent
        #   @return [::String]
        #     Required. The resource name of the Collection for which to create the
        #     Index. Format:
        #     `projects/{project}/locations/{location}/collections/{collection}`
        # @!attribute [rw] index_id
        #   @return [::String]
        #     Required. ID of the Index to create.
        #     The id must be 1-63 characters long, and comply with
        #     [RFC1035](https://www.ietf.org/rfc/rfc1035.txt).
        #     Specifically, it must be 1-63 characters long and match the regular
        #     expression `[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?`.
        # @!attribute [rw] index
        #   @return [::Google::Cloud::VectorSearch::V1::Index]
        #     Required. The resource being created
        # @!attribute [rw] request_id
        #   @return [::String]
        #     Optional. An optional request ID to identify requests. Specify a unique
        #     request ID so that if you must retry your request, the server will know to
        #     ignore the request if it has already been completed. The server will
        #     guarantee that for at least 60 minutes since the first request.
        #
        #     For example, consider a situation where you make an initial request and the
        #     request times out. If you make the request again with the same request
        #     ID, the server can check if original operation with the same request ID
        #     was received, and if so, will ignore the second request. This prevents
        #     clients from accidentally creating duplicate commitments.
        #
        #     The request ID must be a valid UUID with the exception that zero UUID is
        #     not supported (00000000-0000-0000-0000-000000000000).
        class CreateIndexRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Message for updating an Index.
        # @!attribute [rw] index
        #   @return [::Google::Cloud::VectorSearch::V1::Index]
        #     Required. The resource being updated.
        # @!attribute [rw] update_mask
        #   @return [::Google::Protobuf::FieldMask]
        #     Optional. Specifies the fields to be overwritten in the Index resource by
        #     the update. The fields specified in the update_mask are relative to the
        #     resource, not the full request. A field will be overwritten if it is in the
        #     mask. If the user does not provide a mask then all fields present in the
        #     request with non-empty values will be overwritten.
        #
        #     The following fields support update:
        #       * `display_name`
        #       * `description`
        #       * `labels`
        #       * `dedicated_infrastructure.autoscaling_spec.min_replica_count`
        #       * `dedicated_infrastructure.autoscaling_spec.max_replica_count`
        #
        #     If `*` is provided in the `update_mask`, full replacement of mutable fields
        #     will be performed.
        # @!attribute [rw] request_id
        #   @return [::String]
        #     Optional. An optional request ID to identify requests. Specify a unique
        #     request ID so that if you must retry your request, the server will know to
        #     ignore the request if it has already been completed. The server will
        #     guarantee that for at least 60 minutes since the first request.
        #
        #     For example, consider a situation where you make an initial request and the
        #     request times out. If you make the request again with the same request
        #     ID, the server can check if original operation with the same request ID
        #     was received, and if so, will ignore the second request. This prevents
        #     clients from accidentally creating duplicate commitments.
        #
        #     The request ID must be a valid UUID with the exception that zero UUID is
        #     not supported (00000000-0000-0000-0000-000000000000).
        class UpdateIndexRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Message for deleting an Index.
        # @!attribute [rw] name
        #   @return [::String]
        #     Required. The resource name of the Index to delete.
        #     Format:
        #     `projects/{project}/locations/{location}/collections/{collection}/indexes/{index}`
        # @!attribute [rw] request_id
        #   @return [::String]
        #     Optional. An optional request ID to identify requests. Specify a unique
        #     request ID so that if you must retry your request, the server will know to
        #     ignore the request if it has already been completed. The server will
        #     guarantee that for at least 60 minutes since the first request.
        #
        #     For example, consider a situation where you make an initial request and the
        #     request times out. If you make the request again with the same request
        #     ID, the server can check if original operation with the same request ID
        #     was received, and if so, will ignore the second request. This prevents
        #     clients from accidentally creating duplicate commitments.
        #
        #     The request ID must be a valid UUID with the exception that zero UUID is
        #     not supported (00000000-0000-0000-0000-000000000000).
        class DeleteIndexRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Message for requesting list of Indexes
        # @!attribute [rw] parent
        #   @return [::String]
        #     Required. Parent value for ListIndexesRequest
        # @!attribute [rw] page_size
        #   @return [::Integer]
        #     Optional. Requested page size. Server may return fewer items than
        #     requested. If unspecified, server will pick an appropriate default.
        # @!attribute [rw] page_token
        #   @return [::String]
        #     Optional. A token identifying a page of results the server should return.
        # @!attribute [rw] filter
        #   @return [::String]
        #     Optional. Filtering results
        # @!attribute [rw] order_by
        #   @return [::String]
        #     Optional. Hint for how to order the results
        class ListIndexesRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Message for response to listing Indexes
        # @!attribute [rw] indexes
        #   @return [::Array<::Google::Cloud::VectorSearch::V1::Index>]
        #     The list of Index
        # @!attribute [rw] next_page_token
        #   @return [::String]
        #     A token identifying a page of results the server should return.
        class ListIndexesResponse
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Message for getting an Index
        # @!attribute [rw] name
        #   @return [::String]
        #     Required. Name of the resource
        class GetIndexRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Represents the metadata of the long-running operation.
        # @!attribute [r] create_time
        #   @return [::Google::Protobuf::Timestamp]
        #     Output only. The time the operation was created.
        # @!attribute [r] end_time
        #   @return [::Google::Protobuf::Timestamp]
        #     Output only. The time the operation finished running.
        # @!attribute [r] target
        #   @return [::String]
        #     Output only. Server-defined resource path for the target of the operation.
        # @!attribute [r] verb
        #   @return [::String]
        #     Output only. Name of the verb executed by the operation.
        # @!attribute [r] status_message
        #   @return [::String]
        #     Output only. Human-readable status of the operation, if any.
        # @!attribute [r] requested_cancellation
        #   @return [::Boolean]
        #     Output only. Identifies whether the user has requested cancellation
        #     of the operation. Operations that have been cancelled successfully
        #     have
        #     {::Google::Longrunning::Operation#error google.longrunning.Operation.error}
        #     value with a {::Google::Rpc::Status#code google.rpc.Status.code} of `1`,
        #     corresponding to `Code.CANCELLED`.
        # @!attribute [r] api_version
        #   @return [::String]
        #     Output only. API version used to start the operation.
        class OperationMetadata
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Request message for
        # {::Google::Cloud::VectorSearch::V1::VectorSearchService::Client#import_data_objects VectorSearchService.ImportDataObjects}.
        # @!attribute [rw] gcs_import
        #   @return [::Google::Cloud::VectorSearch::V1::ImportDataObjectsRequest::GcsImportConfig]
        #     The Cloud Storage location of the input content.
        # @!attribute [rw] name
        #   @return [::String]
        #     Required. The resource name of the Collection to import DataObjects into.
        #     Format: `projects/{project}/locations/{location}/collections/{collection}`.
        class ImportDataObjectsRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods

          # Google Cloud Storage configuration for the import.
          # @!attribute [rw] contents_uri
          #   @return [::String]
          #     Required. URI prefix of the Cloud Storage DataObjects to import.
          # @!attribute [rw] error_uri
          #   @return [::String]
          #     Required. URI prefix of the Cloud Storage location to write any errors
          #     encountered during the import.
          # @!attribute [rw] output_uri
          #   @return [::String]
          #     Optional. URI prefix of the Cloud Storage location to write DataObject
          #     `IDs` and `etags` of DataObjects that were successfully imported. The
          #     service will write the successfully imported DataObjects to sharded files
          #     under this prefix. If this field is empty, no output will be written.
          class GcsImportConfig
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end
        end

        # Metadata for
        # {::Google::Cloud::VectorSearch::V1::VectorSearchService::Client#import_data_objects VectorSearchService.ImportDataObjects}.
        # @!attribute [r] create_time
        #   @return [::Google::Protobuf::Timestamp]
        #     Output only. The time the operation was created.
        # @!attribute [r] update_time
        #   @return [::Google::Protobuf::Timestamp]
        #     Output only. The time the operation was last updated.
        # @!attribute [r] success_count
        #   @return [::Integer]
        #     Output only. Number of DataObjects that were processed successfully.
        # @!attribute [r] failure_count
        #   @return [::Integer]
        #     Output only. Number of DataObjects that failed during processing.
        class ImportDataObjectsMetadata
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Response for
        # {::Google::Cloud::VectorSearch::V1::VectorSearchService::Client#import_data_objects VectorSearchService.ImportDataObjects}.
        # @!attribute [rw] status
        #   @return [::Google::Rpc::Status]
        #     Status of the LRO
        class ImportDataObjectsResponse
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Request message for
        # {::Google::Cloud::VectorSearch::V1::VectorSearchService::Client#export_data_objects VectorSearchService.ExportDataObjects}.
        # @!attribute [rw] gcs_destination
        #   @return [::Google::Cloud::VectorSearch::V1::ExportDataObjectsRequest::GcsExportDestination]
        #     The Cloud Storage location where user wants to export Data Objects.
        # @!attribute [rw] name
        #   @return [::String]
        #     Required. The resource name of the Collection from which we want to export
        #     Data Objects. Format:
        #     `projects/{project}/locations/{location}/collections/{collection}`.
        # @!attribute [rw] field_filter
        #   @return [::Google::Cloud::VectorSearch::V1::ExportDataObjectsRequest::FieldFilter]
        #     Optional. Restricts which top-level Data Object fields appear in each
        #     exported JSONL record. If unset, every field is exported (the existing
        #     behavior). The primary use case is excluding the per-object `etag` so
        #     that the exported records can be imported into a Collection in a
        #     different region without optimistic-concurrency conflicts.
        #
        #     Allowed field names are `id`, `data`, `vectors`, `etag`.
        class ExportDataObjectsRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods

          # Google Cloud Storage configuration for the export.
          # @!attribute [rw] export_uri
          #   @return [::String]
          #     Required. URI prefix of the Cloud Storage where to export Data Objects.
          #     The bucket is required to be in the same region as the collection.
          # @!attribute [rw] format
          #   @return [::Google::Cloud::VectorSearch::V1::ExportDataObjectsRequest::GcsExportDestination::Format]
          #     Required. The format of the exported Data Objects.
          class GcsExportDestination
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods

            # Options for the format of the exported Data Objects.
            module Format
              # Unspecified format.
              FORMAT_UNSPECIFIED = 0

              # Exports Data Objects in `JSONL` format.
              JSONL = 2
            end
          end

          # Selects which top-level Data Object fields are emitted at export time.
          # @!attribute [rw] included_fields
          #   @return [::Google::Cloud::VectorSearch::V1::ExportDataObjectsRequest::FieldFilter::FieldList]
          #     Optional. Only these top-level fields will appear in each exported
          #     record.
          #
          #     Note: The following fields are mutually exclusive: `included_fields`, `excluded_fields`. If a field in that set is populated, all other fields in the set will automatically be cleared.
          # @!attribute [rw] excluded_fields
          #   @return [::Google::Cloud::VectorSearch::V1::ExportDataObjectsRequest::FieldFilter::FieldList]
          #     Optional. Every top-level field except these will appear in each
          #     exported record.
          #
          #     Note: The following fields are mutually exclusive: `excluded_fields`, `included_fields`. If a field in that set is populated, all other fields in the set will automatically be cleared.
          class FieldFilter
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods

            # Wrapper for a repeated string. Wrapping in a message lets the
            # surrounding `oneof` distinguish "field set to an empty list" (which is
            # rejected as INVALID_ARGUMENT) from "field not set".
            # @!attribute [rw] fields
            #   @return [::Array<::String>]
            #     Required. The list of top-level Data Object JSON field names. Allowed
            #     values are `id`, `data`, `vectors`, `etag`.
            class FieldList
              include ::Google::Protobuf::MessageExts
              extend ::Google::Protobuf::MessageExts::ClassMethods
            end
          end
        end

        # Metadata for the ExportDataObjects LRO.
        # @!attribute [r] create_time
        #   @return [::Google::Protobuf::Timestamp]
        #     Output only. The time the operation was created.
        # @!attribute [r] finish_time
        #   @return [::Google::Protobuf::Timestamp]
        #     Output only. The time the operation finished.
        class ExportDataObjectsMetadata
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Response for the ExportDataObjects LRO.
        class ExportDataObjectsResponse
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Represents dedicated infrastructure for the index.
        # @!attribute [rw] mode
        #   @return [::Google::Cloud::VectorSearch::V1::DedicatedInfrastructure::Mode]
        #     Optional. Mode of the dedicated infrastructure.
        # @!attribute [rw] autoscaling_spec
        #   @return [::Google::Cloud::VectorSearch::V1::DedicatedInfrastructure::AutoscalingSpec]
        #     Optional. Autoscaling specification.
        class DedicatedInfrastructure
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods

          # Specification for autoscaling.
          # @!attribute [rw] min_replica_count
          #   @return [::Integer]
          #     Optional. The minimum number of replicas. If not set or set to `0`,
          #     defaults to `2`. Must be >= `1` and <= `1000`.
          # @!attribute [rw] max_replica_count
          #   @return [::Integer]
          #     Optional. The maximum number of replicas.  Must be >=
          #     `min_replica_count` and <= `1000`.
          #     For the v1beta version, if not set or set to `0`, defaults to
          #     the greater of `min_replica_count` and `5`.
          #     For all other versions, if not set or set to `0`, defaults to
          #     the greater of `min_replica_count` and `2`.
          class AutoscalingSpec
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # Mode of the dedicated infrastructure.
          module Mode
            # Default will use `PERFORMANCE_OPTIMIZED`.
            MODE_UNSPECIFIED = 0

            # This is storage optimized variation.
            STORAGE_OPTIMIZED = 1

            # This is Performance optimized on E2 or equivalent family.
            PERFORMANCE_OPTIMIZED = 2
          end
        end

        # Dense ScaNN index configuration.
        # @!attribute [rw] feature_norm_type
        #   @return [::Google::Cloud::VectorSearch::V1::DenseScannIndex::FeatureNormType]
        #     Optional. Feature norm type.
        class DenseScannIndex
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods

          # Feature norm type for ScaNN index.
          module FeatureNormType
            # Unspecified feature norm type.
            FEATURE_NORM_TYPE_UNSPECIFIED = 0

            # No norm applied.
            NONE = 1

            # Unit L2 norm.
            UNIT_L2_NORM = 2
          end
        end
      end
    end
  end
end
