source "https://rubygems.org"

gemspec

gem "google-cloud-core", path: "../google-cloud-core"
gem "google-cloud-env", path: "../google-cloud-env"
gem "google-cloud-errors", path: "../google-cloud-errors"
gem "google-cloud-automl-v1", path: "../google-cloud-automl-v1"
gem "google-cloud-automl-v1beta1", path: "../google-cloud-automl-v1beta1"
