inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "acceptance/**/*"
    - "google-cloud-datastore.gemspec"
    - "Rakefile"
    - "support/**/*"
    - "test/**/*"

Documentation:
  Enabled: false

Layout/AlignHash:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Naming/FileName:
  Exclude:
    - "lib/google-cloud-datastore.rb"
Naming/RescuedExceptionsVariableName:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
