deep-copy-regex:
  - source: /google/cloud/beyondcorp/appconnections/[^/]+-ruby/(.*)
    dest: /owl-bot-staging/google-cloud-beyond_corp/google-cloud-beyond_corp-app_connections/$1
  - source: /google/cloud/beyondcorp/appconnectors/[^/]+-ruby/(.*)
    dest: /owl-bot-staging/google-cloud-beyond_corp/google-cloud-beyond_corp-app_connectors/$1
  - source: /google/cloud/beyondcorp/appgateways/[^/]+-ruby/(.*)
    dest: /owl-bot-staging/google-cloud-beyond_corp/google-cloud-beyond_corp-app_gateways/$1
  - source: /google/cloud/beyondcorp/clientgateways/[^/]+-ruby/(.*)
    dest: /owl-bot-staging/google-cloud-beyond_corp/google-cloud-beyond_corp-client_gateways/$1
