inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "acceptance/**/*"
    - "google-cloud-language.gemspec"
    - "lib/**/*_pb.rb"
    - "Rakefile"
    - "proto_docs/**/*"
    - "support/**/*"
    - "test/**/*"
