source "https://rubygems.org"

gemspec

gem "gapic-common", github: "googleapis/gapic-generator-ruby"
gem "google-cloud-core", path: "../google-cloud-core"
gem "google-cloud-env", path: "../google-cloud-env"
gem "rake", "~> 11.0"
