source "https://rubygems.org"

gemspec

gem "google-cloud-video_intelligence-v1", path: "../google-cloud-video_intelligence-v1"
gem "google-cloud-video_intelligence-v1beta2", path: "../google-cloud-video_intelligence-v1beta2"
gem "google-cloud-video_intelligence-v1p1beta1", path: "../google-cloud-video_intelligence-v1p1beta1"
gem "google-cloud-video_intelligence-v1p2beta1", path: "../google-cloud-video_intelligence-v1p2beta1"
