AllCops:
  Exclude:
    - "acceptance/**/*"
    - "integration/**/*"
    - "google-cloud-error_reporting.gemspec"
    - "lib/google/devtools/**/*"
    - "lib/google/cloud/error_reporting/v1beta1/**/*"
    - "lib/google/cloud/error_reporting/v1beta1.rb"
    - "Rakefile"
    - "test/**/*"

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/NumericLiterals:
  Enabled: false
Style/SpaceAroundOperators:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/EmptyLines:
  Enabled: false
Style/EmptyElse:
  Enabled: false
Style/HashSyntax:
  Exclude:
    - "lib/google/cloud/error_reporting/v1beta1/**/*"
Metrics/LineLength:
  Exclude:
    - "lib/google/cloud/error_reporting/v1beta1/**/*"
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 25
Metrics/MethodLength:
  Max: 20
  Exclude:
    - "lib/google/cloud/error_reporting/v1beta1/**/*"
Metrics/ParameterLists:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
Style/FileName:
  Enabled: false # for lib/google-cloud-error_reporting.rb file
Lint/RescueException:
  Enabled: false # for lib/google/cloud/error_reporting/middleware.rb file
Lint/AmbiguousOperator:
  Enabled: false # for lib/google/cloud/error_reporting/project.rb file
