source "https://rubygems.org"

gemspec

gem "google-cloud-core", path: "../google-cloud-core"
gem "google-cloud-env", path: "../google-cloud-env"
gem "stackdriver-core", path: "../stackdriver-core"

gem "rake", "~> 13.0.0"
