# Copyright 2016 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


require "bundler/setup"
require "bundler/gem_tasks"

task :test do
  $LOAD_PATH.unshift "lib", "test"
  Dir.glob("test/**/*_test.rb").each { |file| require_relative file }
end

namespace :test do
  desc "Runs tests with coverage."
  task :coverage do
  end
end

desc "Runs acceptance tests."
task :acceptance do
  puts "The google-cloud-error_reporting gem does not have acceptance tests."
end

namespace :acceptance do
  desc "Runs acceptance cleanup."
  task :cleanup do
  end
end

desc "Runs yard-doctest example tests."
task :doctest do
end

task :rubocop do
end

namespace :integration do
  desc "Runs integration tests against GAE"
  task :gae, :project_uri do |t, args|
    fail "You must provide a project_uri. e.g. rake " \
      "integration:gae[http://my-project.appspot.com]" if args[:project_uri].nil?

    ENV["TEST_GOOGLE_CLOUD_PROJECT_URI"] = args[:project_uri]

    $LOAD_PATH.unshift "lib", "integration"
    Dir.glob("integration/gae/**/*_test.rb").each { |file| require_relative file }
  end

  desc "Runs integration tests against GKE"
  task :gke, :pod_name do |t, args|
    fail "You must provide the GKE pod name. e.g. " \
      "rake integration:gke[google-cloud-ruby-test]" if args[:pod_name].nil?

    ENV["TEST_GKE_POD_NAME"] = args[:pod_name]

    $LOAD_PATH.unshift "lib", "integration"
    Dir.glob("integration/gke/**/*_test.rb").each { |file| require_relative file }
  end
end

desc "Start an interactive shell."
task :console do
end

require "yard"
require "yard/rake/yardoc_task"
YARD::Rake::YardocTask.new

desc "Generates JSON output from google-cloud-error_reporting .yardoc"
task :jsondoc => :yard do
  require "rubygems"
  require "gcloud/jsondoc"

  registry = YARD::Registry.load! ".yardoc"
  generator = Gcloud::Jsondoc::Generator.new registry, "google-cloud-error_reporting"
  generator.write_to "jsondoc"
  cp ["docs/instrumentation.md", "docs/toc.json"], "jsondoc", verbose: true
end

task :default => :test
