# Copyright 2016 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


require "bundler/setup"
require "bundler/gem_tasks"

require "rubocop/rake_task"
RuboCop::RakeTask.new

desc "Run tests."
task :test do
  $LOAD_PATH.unshift "lib", "test"
  Dir.glob("test/**/*_test.rb").each { |file| require_relative file }
end

namespace :test do
  desc "Run tests with coverage."
  task :coverage do
  end
end

# Acceptance tests
desc "Run the logging acceptance tests."
task :acceptance, :project, :keyfile do |t, args|
  project = args[:project]
  project ||= ENV["ERROR_REPORTING_TEST_PROJECT"] || ENV["GCLOUD_TEST_PROJECT"]
  keyfile = args[:keyfile]
  keyfile ||= ENV["ERROR_REPORTING_TEST_KEYFILE"] || ENV["GCLOUD_TEST_KEYFILE"]
  if keyfile
    keyfile = File.read keyfile
  else
    keyfile ||= ENV["ERROR_REPORTING_TEST_KEYFILE_JSON"] || ENV["GCLOUD_TEST_KEYFILE_JSON"]
  end
  if project.nil? || keyfile.nil?
    fail "You must provide a project and keyfile. e.g. rake acceptance[test123,/path/to/keyfile.json] " \
      "or ERROR_REPORTING_TEST_PROJECT=test123 ERROR_REPORTING_TEST_KEYFILE=/path/to/keyfile.json rake acceptance"
  end
  # clear any env var already set
  require "google/cloud/error_reporting/credentials"
  (Google::Cloud::ErrorReporting::Credentials::PATH_ENV_VARS +
   Google::Cloud::ErrorReporting::Credentials::JSON_ENV_VARS).each do |path|
    ENV[path] = nil
  end
  # always overwrite when running tests
  ENV["ERROR_REPORTING_PROJECT"] = project
  ENV["ERROR_REPORTING_KEYFILE_JSON"] = keyfile

  Rake::Task["acceptance:run"].invoke
end

namespace :acceptance do
  desc "Run acceptance tests with coverage."
  task :coverage, :project, :keyfile do |t, args|
    require "simplecov"
    SimpleCov.start do
      command_name "google-cloud-error_reporting"
      track_files "lib/**/*.rb"
      add_filter "acceptance/"
    end

    Rake::Task[:acceptance].invoke
  end

  desc "Run acceptance cleanup."
  task :cleanup do
  end

  task :run do
    $LOAD_PATH.unshift "lib", "acceptance"
    Dir.glob("acceptance/error_reporting/**/*_test.rb").each { |file| require_relative file }
  end
end

desc "Run yard-doctest example tests."
task :doctest do
  sh "bundle exec yard config load_plugins true && bundle exec yard doctest"
end

namespace :integration do
  desc "Run integration tests against GAE"
  task :gae, :project_uri do |t, args|
    fail "You must provide a project_uri. e.g. rake " \
      "integration:gae[http://my-project.appspot-preview.com]" if args[:project_uri].nil?

    ENV["TEST_GOOGLE_CLOUD_PROJECT_URI"] = args[:project_uri]

    $LOAD_PATH.unshift "lib", "integration"
    Dir.glob("integration/*_test.rb").each { |file| require_relative file }
    Dir.glob("integration/gae/**/*_test.rb").each { |file| require_relative file }
  end

  desc "Run integration tests against GKE"
  task :gke, :pod_name do |t, args|
    fail "You must provide the GKE pod name. e.g. " \
      "rake integration:gke[google-cloud-ruby-test]" if args[:pod_name].nil?

    ENV["TEST_GKE_POD_NAME"] = args[:pod_name]

    $LOAD_PATH.unshift "lib", "integration"
    Dir.glob("integration/*_test.rb").each { |file| require_relative file }
    Dir.glob("integration/gke/**/*_test.rb").each { |file| require_relative file }
  end
end

desc "Start an interactive shell."
task :console do
  require "irb"
  require "irb/completion"
  require "pp"

  $LOAD_PATH.unshift "lib"

  require "google-cloud-error_reporting"
  def gcloud; @gcloud ||= Google::Cloud.new; end

  ARGV.clear
  IRB.start
end

require "yard"
require "yard/rake/yardoc_task"
YARD::Rake::YardocTask.new do |y|
  # y.options << "--fail-on-warning"
end

desc "Run the CI build"
task :ci do
  header "BUILDING google-cloud-error_reporting"
  header "google-cloud-error_reporting rubocop", "*"
  Rake::Task[:rubocop].invoke
  header "google-cloud-error_reporting yard", "*"
  header "error_reporting yard still had warnings", "!"
  Rake::Task[:yard].invoke
  header "google-cloud-error_reporting doctest", "*"
  Rake::Task[:doctest].invoke
  header "google-cloud-error_reporting test", "*"
  Rake::Task[:test].invoke
end
namespace :ci do
  desc "Run the CI build, with acceptance tests."
  task :acceptance do
    Rake::Task[:ci].invoke
    header "google-cloud-error_reporting acceptance", "*"
    Rake::Task[:acceptance].invoke
  end
  task :a do
    # This is a handy shortcut to save typing
    Rake::Task["ci:acceptance"].invoke
  end
end

task :default => :test

def header str, token = "#"
  line_length = str.length + 8
  puts ""
  puts token * line_length
  puts "#{token * 3} #{str} #{token * 3}"
  puts token * line_length
  puts ""
end
