# Copyright 2016 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


require "bundler/setup"
require "bundler/gem_tasks"

task :test do
end

task :rubocop do
end

namespace :test do
  desc "Runs tests with coverage."
  task :coverage do
  end
end

# Acceptance tests
desc "Runs the lro acceptance tests."
task :acceptance, :project, :keyfile do |_, args|
end

namespace :acceptance do
  desc "Runs acceptance tests with coverage."
  task :coverage, :project, :keyfile do |t, args|
  end


  desc "Runs acceptance cleanup."
  task :cleanup do
  end
end

desc "Runs yard-doctest example tests."
task :doctest do
end

desc "Start an interactive shell."
task :console do
end

desc "Generates JSON output from google-cloud-lro .yardoc"
task :jsondoc do
end

task :default => :test
