source "https://rubygems.org"

gemspec

gem "google-cloud-core", path: "../google-cloud-core"
gem "google-cloud-env", path: "../google-cloud-env"
gem "google-cloud-errors", path: "../google-cloud-errors"
gem "google-cloud-pubsub", path: "../google-cloud-pubsub"

gem "minitest-reporters", "~> 1.3.5", require: false
gem "rake"

gem "minitest"
gem "rubocop-minitest", github: "koic/rubocop-minitest", branch: "fix_false_negative_for_global_expectations_using_without_arguments"
