require "bundler/setup"
require "bundler/gem_tasks"

require "rubocop/rake_task"
RuboCop::RakeTask.new

desc "Run tests."
task :test do
  $LOAD_PATH.unshift "lib", "test"
  Dir.glob("test/**/*_test.rb").each { |file| require_relative file }
end

namespace :test do
  desc "Run tests with coverage."
  task :coverage do
    require "simplecov"
    SimpleCov.start do
      command_name "google-cloud-storage"
      track_files "lib/**/*.rb"
      add_filter "test/"
    end

    Rake::Task["test"].invoke
  end
end

# Acceptance tests
desc "Run the storage acceptance tests."
task :acceptance, :project, :keyfile do |t, args|
  project = args[:project]
  project ||= ENV["GCLOUD_TEST_PROJECT"] || ENV["STORAGE_TEST_PROJECT"]
  keyfile = args[:keyfile]
  keyfile ||= ENV["GCLOUD_TEST_KEYFILE"] || ENV["STORAGE_TEST_KEYFILE"]
  if keyfile
    keyfile = File.read keyfile
  else
    keyfile ||= ENV["GCLOUD_TEST_KEYFILE_JSON"] || ENV["STORAGE_TEST_KEYFILE_JSON"]
  end
  if project.nil? || keyfile.nil?
    fail "You must provide a project and keyfile. e.g. rake acceptance[test123, /path/to/keyfile.json] or STORAGE_TEST_PROJECT=test123 STORAGE_TEST_KEYFILE=/path/to/keyfile.json rake acceptance"
  end
  # always overwrite when running tests
  ENV["STORAGE_PROJECT"] = project
  ENV["STORAGE_KEYFILE"] = nil
  ENV["STORAGE_KEYFILE_JSON"] = keyfile
  ENV["PUBSUB_PROJECT"] = project
  ENV["PUBSUB_KEYFILE"] = nil
  ENV["PUBSUB_KEYFILE_JSON"] = keyfile

  Rake::Task["acceptance:run"].invoke
end

namespace :acceptance do
  desc "Run tests with coverage."
  task :coverage, :project, :keyfile do |t, args|
    require "simplecov"
    SimpleCov.start do
      command_name "google-cloud-storage"
      track_files "lib/**/*.rb"
      add_filter "acceptance/"
    end

    Rake::Task["acceptance"].invoke
  end

  desc "Removes *ALL* buckets and files. Use with caution."
  task :cleanup do |t, args|
    project = args[:project]
    project ||= ENV["GCLOUD_TEST_PROJECT"] || ENV["STORAGE_TEST_PROJECT"]
    keyfile = args[:keyfile]
    keyfile ||= ENV["GCLOUD_TEST_KEYFILE"] || ENV["STORAGE_TEST_KEYFILE"]
    if keyfile
      keyfile = File.read keyfile
    else
      keyfile ||= ENV["GCLOUD_TEST_KEYFILE_JSON"] || ENV["STORAGE_TEST_KEYFILE_JSON"]
    end
    if project.nil? || keyfile.nil?
      fail "You must provide a project and keyfile. e.g. rake acceptance:cleanup[test123, /path/to/keyfile.json] or STORAGE_TEST_PROJECT=test123 STORAGE_TEST_KEYFILE=/path/to/keyfile.json rake acceptance:cleanup"
    end
    # always overwrite when running tests
    ENV["STORAGE_PROJECT"] = project
    ENV["STORAGE_KEYFILE"] = nil
    ENV["STORAGE_KEYFILE_JSON"] = keyfile

    $LOAD_PATH.unshift "lib"
    require "google/cloud/storage"
    puts "Cleaning up Storage buckets and files"
    Google::Cloud.storage.buckets.all do |b|
      begin
        b.files(versions: true).all do |file|
          file.delete generation: true
        end
        # Add one second delay between bucket deletes to avoid rate limiting errors
        sleep 1
        b.delete
      rescue => e
        puts "Error while cleaning up bucket #{b.name}\n\n#{e}"
      end
    end
  end

  task :run do
    $LOAD_PATH.unshift "lib", "acceptance"
    Dir.glob("acceptance/**/*_test.rb").each { |file| require_relative file }
  end
end

desc "Run yard-doctest example tests."
task doctest: :yard do
  sh "bundle exec yard config -a autoload_plugins yard-doctest"
  sh "bundle exec yard doctest"
end

desc "Start an interactive shell."
task :console do
  require "irb"
  require "irb/completion"
  require "pp"

  $LOAD_PATH.unshift "lib"

  require "google-cloud-storage"
  def gcloud; @gcloud ||= Google::Cloud.new; end

  ARGV.clear
  IRB.start
end

require "yard"
require "yard/rake/yardoc_task"
YARD::Rake::YardocTask.new

desc "Generates JSON output from google-cloud-storage .yardoc"
task :jsondoc => :yard do
  require "rubygems"
  require "gcloud/jsondoc"

  registry = YARD::Registry.load! ".yardoc"
  generator = Gcloud::Jsondoc::Generator.new registry, "google-cloud-storage"
  rm_rf "jsondoc", verbose: true
  generator.write_to "jsondoc"
  cp ["docs/authentication.md", "docs/toc.json"], "jsondoc", verbose: true
end

desc "Run the CI build"
task :ci do
  header "BUILDING google-cloud-storage"
  header "google-cloud-storage rubocop", "*"
  sh "bundle exec rake rubocop"
  header "google-cloud-storage jsondoc", "*"
  sh "bundle exec rake jsondoc"
  header "google-cloud-storage doctest", "*"
  sh "bundle exec rake doctest"
  header "google-cloud-storage test", "*"
  sh "bundle exec rake test"
end
namespace :ci do
  desc "Run the CI build, with acceptance tests."
  task :acceptance do
    Rake::Task["ci"].invoke
    header "google-cloud-storage acceptance", "*"
    sh "bundle exec rake acceptance -v"
  end
  task :a do
    # This is a handy shortcut to save typing
    Rake::Task["ci:acceptance"].invoke
  end
end

task :default => :test

def header str, token = "#"
  line_length = str.length + 8
  puts ""
  puts token * line_length
  puts "#{token * 3} #{str} #{token * 3}"
  puts token * line_length
  puts ""
end
