# Copyright 2020 Google, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source "https://rubygems.org"

master = ENV["GOOGLE_CLOUD_SAMPLES_TEST"] == "master"

gem "google-cloud-firestore", path: master ? "../../google-cloud-firestore" : nil
gem "google-cloud-firestore-v1", path: master ? "../../google-cloud-firestore-v1" : nil

group :test do
  gem "google-style", ">= 1.25.1", "< 1.27.2"
  gem "minitest", "~> 5.14"
  gem "minitest-focus", "~> 1.2"
  gem "minitest-hooks", "~> 1.5"
  gem "rake", ">= 12.0"
end
