source "https://rubygems.org"

gemspec
gem "gapic-common", path: "../gapic-common/"

gem "google-cloud-network_connectivity-v1", path: "../google-cloud-network_connectivity-v1"
gem "google-cloud-network_connectivity-v1alpha1", path: "../google-cloud-network_connectivity-v1alpha1"
