source "https://rubygems.org"

gemspec

gem "google-cloud-core", path: "../google-cloud-core"
gem "google-cloud-env", path: "../google-cloud-env"
gem "google-cloud-errors", path: "../google-cloud-errors"
gem "google-cloud-tasks-v2", path: "../google-cloud-tasks-v2"
gem "google-cloud-tasks-v2beta2", path: "../google-cloud-tasks-v2beta2"
gem "google-cloud-tasks-v2beta3", path: "../google-cloud-tasks-v2beta3"
