# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/documentai/v1/processor_type.proto

require 'google/protobuf'

require 'google/api/launch_stage_pb'
require 'google/api/resource_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/cloud/documentai/v1/processor_type.proto", :syntax => :proto3) do
    add_message "google.cloud.documentai.v1.ProcessorType" do
      optional :name, :string, 1
      optional :type, :string, 2
      optional :category, :string, 3
      repeated :available_locations, :message, 4, "google.cloud.documentai.v1.ProcessorType.LocationInfo"
      optional :allow_creation, :bool, 6
      optional :launch_stage, :enum, 8, "google.api.LaunchStage"
    end
    add_message "google.cloud.documentai.v1.ProcessorType.LocationInfo" do
      optional :location_id, :string, 1
    end
  end
end

module Google
  module Cloud
    module DocumentAI
      module V1
        ProcessorType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.documentai.v1.ProcessorType").msgclass
        ProcessorType::LocationInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.documentai.v1.ProcessorType.LocationInfo").msgclass
      end
    end
  end
end
