require "rake/testtask"

task :test_latest do
  raise "Not Implemented"
end

task :test_master do
  start_time = Time.now
  run_task "samples_test_latest"
  end_time = Time.now
  puts "tests took #{(end_time - start_time).to_i} seconds"
end

def run_task task
  Rake::TestTask.new task do |t|
    t.test_files = FileList["**/*_test.rb"]
    t.warning = false
  end
  Rake::Task[task].invoke
end
