require "rake/testtask"

Rake::TestTask.new "test" do |t|
  t.test_files = FileList["**/*_test.rb"]
  t.warning = false
end

task :create_fixtures do
  require_relative "acceptance/helper.rb"
  create_fixtures_bucket
end
