source "https://rubygems.org"

gemspec

gem "google-cloud-recaptcha_enterprise-v1", path: "../google-cloud-recaptcha_enterprise-v1"
gem "google-cloud-recaptcha_enterprise-v1beta1", path: "../google-cloud-recaptcha_enterprise-v1beta1"
