inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "acceptance/**/*"
    - "google-cloud-resource_manager.gemspec"
    - "lib/google/pubsub/**/*"
    - "lib/google/iam/**/*"
    - "Rakefile"
    - "support/**/*"
    - "test/**/*"

Documentation:
  Enabled: false

Layout/AlignHash:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Naming/FileName:
  Exclude:
    - "lib/google-cloud-resource_manager.rb"
Style/IfUnlessModifier:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/WordArray:
  Enabled: false
