inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "lib/**/*_pb.rb"
    - "proto_docs/**/*"
    - "test/**/*"

Metrics/AbcSize:
  Exclude:
    - "lib/google/cloud/service_directory/v1beta1/lookup_service/*.rb"
    - "lib/google/cloud/service_directory/v1beta1/registration_service/*.rb"
Metrics/ClassLength:
  Exclude:
    - "lib/google/cloud/service_directory/v1beta1/lookup_service/*.rb"
    - "lib/google/cloud/service_directory/v1beta1/registration_service/*.rb"
Metrics/CyclomaticComplexity:
  Exclude:
    - "lib/google/cloud/service_directory/v1beta1/lookup_service/*.rb"
    - "lib/google/cloud/service_directory/v1beta1/registration_service/*.rb"
Metrics/LineLength:
  Exclude:
    - "lib/google/cloud/service_directory/v1beta1/lookup_service/*.rb"
    - "lib/google/cloud/service_directory/v1beta1/registration_service/*.rb"
    - "google-cloud-service_directory-v1beta1.gemspec"
Metrics/MethodLength:
  Exclude:
    - "lib/google/cloud/service_directory/v1beta1/lookup_service/*.rb"
    - "lib/google/cloud/service_directory/v1beta1/registration_service/*.rb"
Metrics/PerceivedComplexity:
  Exclude:
    - "lib/google/cloud/service_directory/v1beta1/lookup_service/*.rb"
    - "lib/google/cloud/service_directory/v1beta1/registration_service/*.rb"
Naming/FileName:
  Exclude:
    - "lib/google-cloud-service_directory-v1beta1.rb"
Style/CaseEquality:
  Exclude:
    - "lib/google/cloud/service_directory/v1beta1/lookup_service/*.rb"
    - "lib/google/cloud/service_directory/v1beta1/registration_service/*.rb"
    - "lib/google/cloud/service_directory/v1beta1.rb"
Style/ModuleFunction:
  Enabled: false
