source "https://rubygems.org"

gemspec

gem "google-cloud-discovery_engine-v1", path: "../google-cloud-discovery_engine-v1"
gem "google-cloud-discovery_engine-v1beta", path: "../google-cloud-discovery_engine-v1beta"
