# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: google/shopping/css/v1/accounts_labels.proto for package 'Google.Shopping.Css.V1'
# Original file comments:
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'grpc'
require 'google/shopping/css/v1/accounts_labels_pb'

module Google
  module Shopping
    module Css
      module V1
        module AccountLabelsService
          # Manages Merchant Center and CSS accounts labels.
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'google.shopping.css.v1.AccountLabelsService'

            # Lists the labels owned by an account.
            rpc :ListAccountLabels, ::Google::Shopping::Css::V1::ListAccountLabelsRequest, ::Google::Shopping::Css::V1::ListAccountLabelsResponse
            # Creates a new label, not assigned to any account.
            rpc :CreateAccountLabel, ::Google::Shopping::Css::V1::CreateAccountLabelRequest, ::Google::Shopping::Css::V1::AccountLabel
            # Updates a label.
            rpc :UpdateAccountLabel, ::Google::Shopping::Css::V1::UpdateAccountLabelRequest, ::Google::Shopping::Css::V1::AccountLabel
            # Deletes a label and removes it from all accounts to which it was assigned.
            rpc :DeleteAccountLabel, ::Google::Shopping::Css::V1::DeleteAccountLabelRequest, ::Google::Protobuf::Empty
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
