# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/aiplatform/v1/featurestore_service.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'google/api/client_pb'
require 'google/api/field_behavior_pb'
require 'google/api/resource_pb'
require 'google/cloud/aiplatform/v1/entity_type_pb'
require 'google/cloud/aiplatform/v1/feature_pb'
require 'google/cloud/aiplatform/v1/feature_selector_pb'
require 'google/cloud/aiplatform/v1/featurestore_pb'
require 'google/cloud/aiplatform/v1/io_pb'
require 'google/cloud/aiplatform/v1/operation_pb'
require 'google/longrunning/operations_pb'
require 'google/protobuf/field_mask_pb'
require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/cloud/aiplatform/v1/featurestore_service.proto", :syntax => :proto3) do
    add_message "google.cloud.aiplatform.v1.CreateFeaturestoreRequest" do
      optional :parent, :string, 1
      optional :featurestore, :message, 2, "google.cloud.aiplatform.v1.Featurestore"
      optional :featurestore_id, :string, 3
    end
    add_message "google.cloud.aiplatform.v1.GetFeaturestoreRequest" do
      optional :name, :string, 1
    end
    add_message "google.cloud.aiplatform.v1.ListFeaturestoresRequest" do
      optional :parent, :string, 1
      optional :filter, :string, 2
      optional :page_size, :int32, 3
      optional :page_token, :string, 4
      optional :order_by, :string, 5
      optional :read_mask, :message, 6, "google.protobuf.FieldMask"
    end
    add_message "google.cloud.aiplatform.v1.ListFeaturestoresResponse" do
      repeated :featurestores, :message, 1, "google.cloud.aiplatform.v1.Featurestore"
      optional :next_page_token, :string, 2
    end
    add_message "google.cloud.aiplatform.v1.UpdateFeaturestoreRequest" do
      optional :featurestore, :message, 1, "google.cloud.aiplatform.v1.Featurestore"
      optional :update_mask, :message, 2, "google.protobuf.FieldMask"
    end
    add_message "google.cloud.aiplatform.v1.DeleteFeaturestoreRequest" do
      optional :name, :string, 1
      optional :force, :bool, 2
    end
    add_message "google.cloud.aiplatform.v1.ImportFeatureValuesRequest" do
      optional :entity_type, :string, 1
      optional :entity_id_field, :string, 5
      repeated :feature_specs, :message, 8, "google.cloud.aiplatform.v1.ImportFeatureValuesRequest.FeatureSpec"
      optional :disable_online_serving, :bool, 9
      optional :worker_count, :int32, 11
      optional :disable_ingestion_analysis, :bool, 12
      oneof :source do
        optional :avro_source, :message, 2, "google.cloud.aiplatform.v1.AvroSource"
        optional :bigquery_source, :message, 3, "google.cloud.aiplatform.v1.BigQuerySource"
        optional :csv_source, :message, 4, "google.cloud.aiplatform.v1.CsvSource"
      end
      oneof :feature_time_source do
        optional :feature_time_field, :string, 6
        optional :feature_time, :message, 7, "google.protobuf.Timestamp"
      end
    end
    add_message "google.cloud.aiplatform.v1.ImportFeatureValuesRequest.FeatureSpec" do
      optional :id, :string, 1
      optional :source_field, :string, 2
    end
    add_message "google.cloud.aiplatform.v1.ImportFeatureValuesResponse" do
      optional :imported_entity_count, :int64, 1
      optional :imported_feature_value_count, :int64, 2
      optional :invalid_row_count, :int64, 6
      optional :timestamp_outside_retention_rows_count, :int64, 4
    end
    add_message "google.cloud.aiplatform.v1.BatchReadFeatureValuesRequest" do
      optional :featurestore, :string, 1
      optional :destination, :message, 4, "google.cloud.aiplatform.v1.FeatureValueDestination"
      repeated :pass_through_fields, :message, 8, "google.cloud.aiplatform.v1.BatchReadFeatureValuesRequest.PassThroughField"
      repeated :entity_type_specs, :message, 7, "google.cloud.aiplatform.v1.BatchReadFeatureValuesRequest.EntityTypeSpec"
      oneof :read_option do
        optional :csv_read_instances, :message, 3, "google.cloud.aiplatform.v1.CsvSource"
        optional :bigquery_read_instances, :message, 5, "google.cloud.aiplatform.v1.BigQuerySource"
      end
    end
    add_message "google.cloud.aiplatform.v1.BatchReadFeatureValuesRequest.PassThroughField" do
      optional :field_name, :string, 1
    end
    add_message "google.cloud.aiplatform.v1.BatchReadFeatureValuesRequest.EntityTypeSpec" do
      optional :entity_type_id, :string, 1
      optional :feature_selector, :message, 2, "google.cloud.aiplatform.v1.FeatureSelector"
      repeated :settings, :message, 3, "google.cloud.aiplatform.v1.DestinationFeatureSetting"
    end
    add_message "google.cloud.aiplatform.v1.ExportFeatureValuesRequest" do
      optional :entity_type, :string, 1
      optional :destination, :message, 4, "google.cloud.aiplatform.v1.FeatureValueDestination"
      optional :feature_selector, :message, 5, "google.cloud.aiplatform.v1.FeatureSelector"
      repeated :settings, :message, 6, "google.cloud.aiplatform.v1.DestinationFeatureSetting"
      oneof :mode do
        optional :snapshot_export, :message, 3, "google.cloud.aiplatform.v1.ExportFeatureValuesRequest.SnapshotExport"
        optional :full_export, :message, 7, "google.cloud.aiplatform.v1.ExportFeatureValuesRequest.FullExport"
      end
    end
    add_message "google.cloud.aiplatform.v1.ExportFeatureValuesRequest.SnapshotExport" do
      optional :snapshot_time, :message, 1, "google.protobuf.Timestamp"
      optional :start_time, :message, 2, "google.protobuf.Timestamp"
    end
    add_message "google.cloud.aiplatform.v1.ExportFeatureValuesRequest.FullExport" do
      optional :start_time, :message, 2, "google.protobuf.Timestamp"
      optional :end_time, :message, 1, "google.protobuf.Timestamp"
    end
    add_message "google.cloud.aiplatform.v1.DestinationFeatureSetting" do
      optional :feature_id, :string, 1
      optional :destination_field, :string, 2
    end
    add_message "google.cloud.aiplatform.v1.FeatureValueDestination" do
      oneof :destination do
        optional :bigquery_destination, :message, 1, "google.cloud.aiplatform.v1.BigQueryDestination"
        optional :tfrecord_destination, :message, 2, "google.cloud.aiplatform.v1.TFRecordDestination"
        optional :csv_destination, :message, 3, "google.cloud.aiplatform.v1.CsvDestination"
      end
    end
    add_message "google.cloud.aiplatform.v1.ExportFeatureValuesResponse" do
    end
    add_message "google.cloud.aiplatform.v1.BatchReadFeatureValuesResponse" do
    end
    add_message "google.cloud.aiplatform.v1.CreateEntityTypeRequest" do
      optional :parent, :string, 1
      optional :entity_type, :message, 2, "google.cloud.aiplatform.v1.EntityType"
      optional :entity_type_id, :string, 3
    end
    add_message "google.cloud.aiplatform.v1.GetEntityTypeRequest" do
      optional :name, :string, 1
    end
    add_message "google.cloud.aiplatform.v1.ListEntityTypesRequest" do
      optional :parent, :string, 1
      optional :filter, :string, 2
      optional :page_size, :int32, 3
      optional :page_token, :string, 4
      optional :order_by, :string, 5
      optional :read_mask, :message, 6, "google.protobuf.FieldMask"
    end
    add_message "google.cloud.aiplatform.v1.ListEntityTypesResponse" do
      repeated :entity_types, :message, 1, "google.cloud.aiplatform.v1.EntityType"
      optional :next_page_token, :string, 2
    end
    add_message "google.cloud.aiplatform.v1.UpdateEntityTypeRequest" do
      optional :entity_type, :message, 1, "google.cloud.aiplatform.v1.EntityType"
      optional :update_mask, :message, 2, "google.protobuf.FieldMask"
    end
    add_message "google.cloud.aiplatform.v1.DeleteEntityTypeRequest" do
      optional :name, :string, 1
      optional :force, :bool, 2
    end
    add_message "google.cloud.aiplatform.v1.CreateFeatureRequest" do
      optional :parent, :string, 1
      optional :feature, :message, 2, "google.cloud.aiplatform.v1.Feature"
      optional :feature_id, :string, 3
    end
    add_message "google.cloud.aiplatform.v1.BatchCreateFeaturesRequest" do
      optional :parent, :string, 1
      repeated :requests, :message, 2, "google.cloud.aiplatform.v1.CreateFeatureRequest"
    end
    add_message "google.cloud.aiplatform.v1.BatchCreateFeaturesResponse" do
      repeated :features, :message, 1, "google.cloud.aiplatform.v1.Feature"
    end
    add_message "google.cloud.aiplatform.v1.GetFeatureRequest" do
      optional :name, :string, 1
    end
    add_message "google.cloud.aiplatform.v1.ListFeaturesRequest" do
      optional :parent, :string, 1
      optional :filter, :string, 2
      optional :page_size, :int32, 3
      optional :page_token, :string, 4
      optional :order_by, :string, 5
      optional :read_mask, :message, 6, "google.protobuf.FieldMask"
      optional :latest_stats_count, :int32, 7
    end
    add_message "google.cloud.aiplatform.v1.ListFeaturesResponse" do
      repeated :features, :message, 1, "google.cloud.aiplatform.v1.Feature"
      optional :next_page_token, :string, 2
    end
    add_message "google.cloud.aiplatform.v1.SearchFeaturesRequest" do
      optional :location, :string, 1
      optional :query, :string, 3
      optional :page_size, :int32, 4
      optional :page_token, :string, 5
    end
    add_message "google.cloud.aiplatform.v1.SearchFeaturesResponse" do
      repeated :features, :message, 1, "google.cloud.aiplatform.v1.Feature"
      optional :next_page_token, :string, 2
    end
    add_message "google.cloud.aiplatform.v1.UpdateFeatureRequest" do
      optional :feature, :message, 1, "google.cloud.aiplatform.v1.Feature"
      optional :update_mask, :message, 2, "google.protobuf.FieldMask"
    end
    add_message "google.cloud.aiplatform.v1.DeleteFeatureRequest" do
      optional :name, :string, 1
    end
    add_message "google.cloud.aiplatform.v1.CreateFeaturestoreOperationMetadata" do
      optional :generic_metadata, :message, 1, "google.cloud.aiplatform.v1.GenericOperationMetadata"
    end
    add_message "google.cloud.aiplatform.v1.UpdateFeaturestoreOperationMetadata" do
      optional :generic_metadata, :message, 1, "google.cloud.aiplatform.v1.GenericOperationMetadata"
    end
    add_message "google.cloud.aiplatform.v1.ImportFeatureValuesOperationMetadata" do
      optional :generic_metadata, :message, 1, "google.cloud.aiplatform.v1.GenericOperationMetadata"
      optional :imported_entity_count, :int64, 2
      optional :imported_feature_value_count, :int64, 3
      optional :invalid_row_count, :int64, 6
      optional :timestamp_outside_retention_rows_count, :int64, 7
    end
    add_message "google.cloud.aiplatform.v1.ExportFeatureValuesOperationMetadata" do
      optional :generic_metadata, :message, 1, "google.cloud.aiplatform.v1.GenericOperationMetadata"
    end
    add_message "google.cloud.aiplatform.v1.BatchReadFeatureValuesOperationMetadata" do
      optional :generic_metadata, :message, 1, "google.cloud.aiplatform.v1.GenericOperationMetadata"
    end
    add_message "google.cloud.aiplatform.v1.CreateEntityTypeOperationMetadata" do
      optional :generic_metadata, :message, 1, "google.cloud.aiplatform.v1.GenericOperationMetadata"
    end
    add_message "google.cloud.aiplatform.v1.CreateFeatureOperationMetadata" do
      optional :generic_metadata, :message, 1, "google.cloud.aiplatform.v1.GenericOperationMetadata"
    end
    add_message "google.cloud.aiplatform.v1.BatchCreateFeaturesOperationMetadata" do
      optional :generic_metadata, :message, 1, "google.cloud.aiplatform.v1.GenericOperationMetadata"
    end
  end
end

module Google
  module Cloud
    module AIPlatform
      module V1
        CreateFeaturestoreRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.CreateFeaturestoreRequest").msgclass
        GetFeaturestoreRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.GetFeaturestoreRequest").msgclass
        ListFeaturestoresRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.ListFeaturestoresRequest").msgclass
        ListFeaturestoresResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.ListFeaturestoresResponse").msgclass
        UpdateFeaturestoreRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.UpdateFeaturestoreRequest").msgclass
        DeleteFeaturestoreRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.DeleteFeaturestoreRequest").msgclass
        ImportFeatureValuesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.ImportFeatureValuesRequest").msgclass
        ImportFeatureValuesRequest::FeatureSpec = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.ImportFeatureValuesRequest.FeatureSpec").msgclass
        ImportFeatureValuesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.ImportFeatureValuesResponse").msgclass
        BatchReadFeatureValuesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.BatchReadFeatureValuesRequest").msgclass
        BatchReadFeatureValuesRequest::PassThroughField = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.BatchReadFeatureValuesRequest.PassThroughField").msgclass
        BatchReadFeatureValuesRequest::EntityTypeSpec = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.BatchReadFeatureValuesRequest.EntityTypeSpec").msgclass
        ExportFeatureValuesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.ExportFeatureValuesRequest").msgclass
        ExportFeatureValuesRequest::SnapshotExport = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.ExportFeatureValuesRequest.SnapshotExport").msgclass
        ExportFeatureValuesRequest::FullExport = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.ExportFeatureValuesRequest.FullExport").msgclass
        DestinationFeatureSetting = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.DestinationFeatureSetting").msgclass
        FeatureValueDestination = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.FeatureValueDestination").msgclass
        ExportFeatureValuesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.ExportFeatureValuesResponse").msgclass
        BatchReadFeatureValuesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.BatchReadFeatureValuesResponse").msgclass
        CreateEntityTypeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.CreateEntityTypeRequest").msgclass
        GetEntityTypeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.GetEntityTypeRequest").msgclass
        ListEntityTypesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.ListEntityTypesRequest").msgclass
        ListEntityTypesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.ListEntityTypesResponse").msgclass
        UpdateEntityTypeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.UpdateEntityTypeRequest").msgclass
        DeleteEntityTypeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.DeleteEntityTypeRequest").msgclass
        CreateFeatureRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.CreateFeatureRequest").msgclass
        BatchCreateFeaturesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.BatchCreateFeaturesRequest").msgclass
        BatchCreateFeaturesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.BatchCreateFeaturesResponse").msgclass
        GetFeatureRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.GetFeatureRequest").msgclass
        ListFeaturesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.ListFeaturesRequest").msgclass
        ListFeaturesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.ListFeaturesResponse").msgclass
        SearchFeaturesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.SearchFeaturesRequest").msgclass
        SearchFeaturesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.SearchFeaturesResponse").msgclass
        UpdateFeatureRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.UpdateFeatureRequest").msgclass
        DeleteFeatureRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.DeleteFeatureRequest").msgclass
        CreateFeaturestoreOperationMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.CreateFeaturestoreOperationMetadata").msgclass
        UpdateFeaturestoreOperationMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.UpdateFeaturestoreOperationMetadata").msgclass
        ImportFeatureValuesOperationMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.ImportFeatureValuesOperationMetadata").msgclass
        ExportFeatureValuesOperationMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.ExportFeatureValuesOperationMetadata").msgclass
        BatchReadFeatureValuesOperationMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.BatchReadFeatureValuesOperationMetadata").msgclass
        CreateEntityTypeOperationMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.CreateEntityTypeOperationMetadata").msgclass
        CreateFeatureOperationMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.CreateFeatureOperationMetadata").msgclass
        BatchCreateFeaturesOperationMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.aiplatform.v1.BatchCreateFeaturesOperationMetadata").msgclass
      end
    end
  end
end
