source "https://rubygems.org"

gemspec

gem "google-cloud-core", path: "../google-cloud-core"
gem "google-cloud-env", path: "../google-cloud-env"
gem "google-cloud-errors", path: "../google-cloud-errors"
gem "google-cloud-vision-v1", path: "../google-cloud-vision-v1"
gem "google-cloud-vision-v1p3beta1", path: "../google-cloud-vision-v1p3beta1"
