inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "google-analytics-data-v1alpha.gemspec"
    - "lib/**/*_pb.rb"
    - "proto_docs/**/*"
    - "test/**/*"
    - "acceptance/**/*"
    - "Rakefile"

Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/FileName:
  Exclude:
    - "lib/google-analytics-data-v1alpha.rb"
Style/AsciiComments:
  Enabled: false
Style/CaseEquality:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
