# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source "https://rubygems.org"

master = ENV["GOOGLE_CLOUD_SAMPLES_TEST"] == "master"

gem "google-cloud-tasks", path: master ? "../../google-cloud-tasks" : nil
gem "google-cloud-tasks-v2", path: master ? "../../google-cloud-tasks-v2" : nil
gem "google-cloud-tasks-v2beta2", path: master ? "../../google-cloud-tasks-v2beta2" : nil
gem "google-cloud-tasks-v2beta3", path: master ? "../../google-cloud-tasks-v2beta3" : nil

group :test do
  gem "rack-test"
  gem "minitest", ">= 5.13", "< 7"
  gem "rake"
end
