# frozen_string_literal: true

# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!

require "gapic/common"
require "gapic/config"
require "gapic/config/method"

require "google/cloud/maintenance/api/v1beta/version"

require "google/cloud/maintenance/api/v1beta/maintenance/credentials"
require "google/cloud/maintenance/api/v1beta/maintenance/paths"
require "google/cloud/maintenance/api/v1beta/maintenance/client"
require "google/cloud/maintenance/api/v1beta/maintenance/rest"

module Google
  module Cloud
    module Maintenance
      module Api
        module V1beta
          ##
          # Unified Maintenance service
          #
          # @example Load this service and instantiate a gRPC client
          #
          #     require "google/cloud/maintenance/api/v1beta/maintenance"
          #     client = ::Google::Cloud::Maintenance::Api::V1beta::Maintenance::Client.new
          #
          # @example Load this service and instantiate a REST client
          #
          #     require "google/cloud/maintenance/api/v1beta/maintenance/rest"
          #     client = ::Google::Cloud::Maintenance::Api::V1beta::Maintenance::Rest::Client.new
          #
          module Maintenance
          end
        end
      end
    end
  end
end

helper_path = ::File.join __dir__, "maintenance", "helpers.rb"
require "google/cloud/maintenance/api/v1beta/maintenance/helpers" if ::File.file? helper_path
