source "https://rubygems.org"

gemspec

gem "autotest-suffix", "~> 1.1"
gem "google-cloud-core", path: "../google-cloud-core"
gem "google-cloud-error_reporting", path: "../google-cloud-error_reporting"
gem "google-cloud-errors", path: "../google-cloud-errors"
gem "google-cloud-logging-v2", path: "../google-cloud-logging-v2"
gem "google-cloud-storage", path: "../google-cloud-storage"
gem "google-style", "~> 1.27.1"
gem "minitest", "~> 5.16"
gem "minitest-autotest", "~> 1.0"
gem "minitest-focus", "~> 1.1"
gem "minitest-reporters", ">= 1.5.0", "< 1.7.2", require: false
gem "minitest-rg", "~> 5.2"
gem "rack", ">= 0.1"
gem "railties", ">= 5.0", "< 7.1.4"
gem "rake"
gem "redcarpet", "~> 3.0"
gem "simplecov", "~> 0.9"
gem "stackdriver-core", path: "../stackdriver-core"
gem "yard", "~> 0.9"
gem "yard-doctest", "~> 0.1.13"
