source "https://rubygems.org"

gemspec

gem "google-cloud-core", path: "../google-cloud-core"
gem "google-cloud-error_reporting", path: "../google-cloud-error_reporting"
gem "google-cloud-errors", path: "../google-cloud-errors"
gem "google-cloud-logging-v2", path: "../google-cloud-logging-v2"
gem "google-cloud-storage", path: "../google-cloud-storage"
gem "stackdriver-core", path: "../stackdriver-core"

gem "minitest-reporters", "~> 1.5.0", require: false
gem "rake"
