source "https://rubygems.org"

gemspec

gem "google-cloud-core", path: "../google-cloud-core"
gem "google-cloud-env", path: "../google-cloud-env"
gem "google-cloud-storage", path: "../google-cloud-storage"
gem "stackdriver-core", path: "../stackdriver-core"

gem "rake", "~> 12.3"
gem "minitest-reporters", "~> 1.3.5"
