require "bundler/setup"
require "bundler/gem_tasks"

require "rubocop/rake_task"
RuboCop::RakeTask.new

desc "Run tests."
task :test do
  $LOAD_PATH.unshift "lib", "test"
  Dir.glob("test/**/*_test.rb").each { |file| require_relative file }
end

namespace :test do
  desc "Run tests with coverage."
  task :coverage do
    require "simplecov"
    SimpleCov.start do
      command_name "google-cloud-logging"
      track_files "lib/**/*.rb"
      add_filter "test/"
      add_filter "lib/google/logging/"
      add_filter "lib/google/cloud/logging/v2/"
    end

    Rake::Task["test"].invoke
  end
end

# Acceptance tests
desc "Run the logging acceptance tests."
task :acceptance, :project, :keyfile do |t, args|
  project = args[:project]
  project ||= ENV["LOGGING_TEST_PROJECT"] || ENV["GCLOUD_TEST_PROJECT"]
  keyfile = args[:keyfile]
  keyfile ||= ENV["LOGGING_TEST_KEYFILE"] || ENV["GCLOUD_TEST_KEYFILE"]
  if keyfile
    keyfile = File.read keyfile
  else
    keyfile ||= ENV["LOGGING_TEST_KEYFILE_JSON"] || ENV["GCLOUD_TEST_KEYFILE_JSON"]
  end
  if project.nil? || keyfile.nil?
    fail "You must provide a project and keyfile. e.g. rake acceptance[test123, /path/to/keyfile.json] or LOGGING_TEST_PROJECT=test123 LOGGING_TEST_KEYFILE=/path/to/keyfile.json rake acceptance"
  end
  # clear any env var already set
  require "google/cloud/logging/credentials"
  (Google::Cloud::Logging::Credentials::PATH_ENV_VARS +
   Google::Cloud::Logging::Credentials::JSON_ENV_VARS).each do |path|
    ENV[path] = nil
  end
  # always overwrite when running tests
  ENV["LOGGING_PROJECT"] = project
  ENV["LOGGING_KEYFILE_JSON"] = keyfile

  Rake::Task["acceptance:run"].invoke
end

namespace :acceptance do
  desc "Run acceptance tests with coverage."
  task :coverage, :project, :keyfile do |t, args|
    require "simplecov"
    SimpleCov.start do
      command_name "google-cloud-logging"
      track_files "lib/**/*.rb"
      add_filter "acceptance/"
    end

    Rake::Task["acceptance"].invoke
  end

  desc "Removes *ALL* Logging logs, sinks, and metrics. Use with caution."
  task :cleanup do |t, args|
    project = args[:project]
    project ||= ENV["LOGGING_TEST_PROJECT"] || ENV["GCLOUD_TEST_PROJECT"]
    keyfile = args[:keyfile]
    keyfile ||= ENV["LOGGING_TEST_KEYFILE"] || ENV["GCLOUD_TEST_KEYFILE"]
    if keyfile
      keyfile = File.read keyfile
    else
      keyfile ||= ENV["LOGGING_TEST_KEYFILE_JSON"] || ENV["GCLOUD_TEST_KEYFILE_JSON"]
    end
    if project.nil? || keyfile.nil?
      fail "You must provide a project and keyfile. e.g. rake acceptance:cleanup[test123, /path/to/keyfile.json] or LOGGING_TEST_PROJECT=test123 LOGGING_TEST_KEYFILE=/path/to/keyfile.json rake acceptance:cleanup"
    end
    # clear any env var already set
    require "google/cloud/logging/credentials"
    (Google::Cloud::Logging::Credentials::PATH_ENV_VARS +
     Google::Cloud::Logging::Credentials::JSON_ENV_VARS).each do |path|
      ENV[path] = nil
    end
    # always overwrite when running tests
    ENV["LOGGING_PROJECT"] = project
    ENV["LOGGING_KEYFILE_JSON"] = keyfile

    $LOAD_PATH.unshift "lib"
    require "google/cloud/logging"
    puts "Cleaning up LOGGING logs, sinks, and metrics"
    begin
      logging = Google::Cloud.logging
      # only delete acceptance logs, not the other logs needed for project.
      logging.logs.select { |l| l.include? "gcloud_ruby_acceptance" }.each { |l| logging.delete_log l }
      # logging.sinks.all &:delete
      logging.metrics.all &:delete
    rescue Google::Cloud::Error => e
      puts e.message
    end
  end

  task :run do
    $LOAD_PATH.unshift "lib", "acceptance"
    Dir.glob("acceptance/logging/**/*_test.rb").each { |file| require_relative file }
  end
end

desc "Run yard-doctest example tests."
task doctest: :yard do
  sh "bundle exec yard config -a autoload_plugins yard-doctest"
  sh "bundle exec yard doctest"
end

namespace :integration do
  desc "Run integration tests against GAE"
  task :gae, :project_uri do |t, args|
    raise "You must provide a project_uri. e.g. rake " \
      "integration:gae[http://my-project.appspot-preview.com]" if args[:project_uri].nil?

    ENV["TEST_GOOGLE_CLOUD_PROJECT_URI"] = args[:project_uri]

    $LOAD_PATH.unshift "lib", "integration"
    Dir.glob("integration/*_test.rb").each { |file| require_relative file }
    Dir.glob("integration/gae/**/*_test.rb").each { |file| require_relative file }
  end

  desc "Run integration tests against GKE"
  task :gke, :pod_name do |t, args|
    fail "You must provide the GKE pod name. e.g. " \
      "rake integration:gke[google-cloud-ruby-test]" if args[:pod_name].nil?

    ENV["TEST_GKE_POD_NAME"] = args[:pod_name]

    $LOAD_PATH.unshift "lib", "integration"
    Dir.glob("integration/*_test.rb").each { |file| require_relative file }
    Dir.glob("integration/gke/**/*_test.rb").each { |file| require_relative file }
  end
end

desc "Start an interactive shell."
task :console do
  require "irb"
  require "irb/completion"
  require "pp"

  $LOAD_PATH.unshift "lib"

  require "google-cloud-logging"
  def gcloud; @gcloud ||= Google::Cloud.new; end

  ARGV.clear
  IRB.start
end

require "yard"
require "yard/rake/yardoc_task"
YARD::Rake::YardocTask.new

desc "Generates JSON output from google-cloud-logging .yardoc"
task :jsondoc => :yard do
  require "rubygems"
  require "gcloud/jsondoc"

  registry = YARD::Registry.load! ".yardoc"

  toc_config = {
    documents: [
      {
        type: "toc",
        title: "Google::Logging::V2::DataTypes",
        modules: [
          {
            title: "Google::Logging::V2",
            include: ["google/logging/v2"]
          },
          {
            title: "Google::Logging::Type",
            include: ["google/logging/type"]
          },
          {
            title: "Google::Api",
            include: ["google/api"]
          },
          {
            title: "Google::Protobuf",
            include: ["google/protobuf"]
          }
        ]
      }
    ]
  }

  generator = Gcloud::Jsondoc::Generator.new registry,
                                             "google-cloud-logging",
                                             generate: toc_config
  rm_rf "jsondoc", verbose: true
  generator.write_to "jsondoc"
  cp ["docs/authentication.md", "docs/instrumentation.md", "docs/toc.json"], "jsondoc", verbose: true
end

desc "Run the CI build"
task :ci do
  header "BUILDING google-cloud-logging"
  header "google-cloud-logging rubocop", "*"
  sh "bundle exec rake rubocop"
  header "google-cloud-logging jsondoc", "*"
  sh "bundle exec rake jsondoc"
  header "google-cloud-logging doctest", "*"
  sh "bundle exec rake doctest"
  header "google-cloud-logging test", "*"
  sh "bundle exec rake test"
end
namespace :ci do
  desc "Run the CI build, with acceptance tests."
  task :acceptance do
    Rake::Task["ci"].invoke
    header "google-cloud-logging acceptance", "*"
    sh "bundle exec rake acceptance -v"
  end
  task :a do
    # This is a handy shortcut to save typing
    Rake::Task["ci:acceptance"].invoke
  end
end

task :default => :test

def header str, token = "#"
  line_length = str.length + 8
  puts ""
  puts token * line_length
  puts "#{token * 3} #{str} #{token * 3}"
  puts token * line_length
  puts ""
end
