# frozen_string_literal: true

source "https://rubygems.org"

gem "google-cloud-bigtable", path: "../../"
gem "grpc", "~> 1.62"
gem "grpc-tools", "~> 1.62"
gem "googleapis-common-protos", "~> 1.5"
gem "googleapis-common-protos-types", "~> 1.14"
