source "https://rubygems.org"

gemspec

gem "google-cloud-core", path: "../google-cloud-core"
gem "google-cloud-env", path: "../google-cloud-env"
gem "google-cloud-errors", path: "../google-cloud-errors"
gem "google-cloud-os_login-v1", path: "../google-cloud-os_login-v1"
gem "google-cloud-os_login-v1beta", path: "../google-cloud-os_login-v1beta"
