source "https://rubygems.org"

gemspec
gem "gapic-common", path: "../gapic-common/"

gem "google-cloud-os_login-v1", path: "../google-cloud-os_login-v1"
gem "google-cloud-os_login-v1beta", path: "../google-cloud-os_login-v1beta"
