source "https://rubygems.org"

gemspec

local_dependencies = ["google-cloud-maintenance-api-v1beta"]

main_spec = gemspecs.last || Bundler.load_gemspec(File.join(__dir__, "google-cloud-maintenance-api.gemspec"))
local_dependencies.each do |name|
  spec_path = File.expand_path "../#{name}/#{name}.gemspec", __dir__
  unless File.file? spec_path
    warn "WARNING: Disabled local dependency for #{name} because gemspec not found."
    next
  end
  version = Bundler.load_gemspec(spec_path).version
  if main_spec.dependencies.any? { |dep| dep.name == name && !dep.requirement.satisfied_by?(version) }
    warn "WARNING: Disabled local dependency for #{name} because the gemspec disallows version #{version}."
    next
  end
  gem name, path: "../#{name}"
end

gem "google-style", "~> 1.30.1"
gem "minitest", ">= 5.22", "< 7"
gem "minitest-focus", "~> 1.4"
gem "minitest-rg", "~> 5.3"
gem "rake", ">= 13.0"
gem "redcarpet", "~> 3.6"
gem "yard", "~> 0.9"
