inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "test/**/*"

Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "Rakefile"
Metrics/ModuleLength:
  Exclude:
    - "lib/stackdriver/core/async_actor.rb"
Metrics/ClassLength:
  Exclude:
    - "lib/stackdriver/core/trace_context.rb"
Naming/AccessorMethodName:
  Exclude:
    - "lib/stackdriver/core/async_actor.rb"
Naming/FileName:
  Exclude:
    - "lib/stackdriver-core.rb"
