source "https://rubygems.org"

gemspec

gem "google-cloud-policy_troubleshooter-v1", path: "../google-cloud-policy_troubleshooter-v1"
gem "google-cloud-policy_troubleshooter-iam-v3", path: "../google-cloud-policy_troubleshooter-iam-v3"
