source "https://rubygems.org"

gemspec

gem "autotest-suffix", "~> 1.1"
gem "avro", "~> 1.10"
gem "bigdecimal", "~> 3.0"
gem "google-cloud-core", path: "../google-cloud-core"
gem "google-cloud-errors", path: "../google-cloud-errors"
gem "google-cloud-pubsub-v1", path: "../google-cloud-pubsub-v1"
gem "google-style", "~> 1.27.1"
gem "minitest", "~> 5.16"
gem "minitest-autotest", "~> 1.0"
gem "minitest-focus", "~> 1.1"
gem "minitest-reporters", "~> 1.5.0", require: false
gem "minitest-rg", "~> 5.2"
gem "pry", ">= 0.14.1", "< 0.16"
gem "rake"
gem "redcarpet", "~> 3.0"
gem "retriable", "~> 3.1"
gem "simplecov", "~> 0.9"
gem "yard", "~> 0.9"
gem "yard-doctest", "~> 0.1.13"
