source "https://rubygems.org"

gemspec

local_dependencies = ["google-cloud-pubsub-v1", "google-cloud-core", "google-cloud-errors"]

main_spec = gemspecs.last || Bundler.load_gemspec(File.join(__dir__, "google-cloud-pubsub.gemspec"))
local_dependencies.each do |name|
  spec_path = File.expand_path "../#{name}/#{name}.gemspec", __dir__
  unless File.file? spec_path
    warn "WARNING: Disabled local dependency for #{name} because gemspec not found."
    next
  end
  version = Bundler.load_gemspec(spec_path).version
  if main_spec.dependencies.any? { |dep| dep.name == name && !dep.requirement.satisfied_by?(version) }
    warn "WARNING: Disabled local dependency for #{name} because the gemspec disallows version #{version}."
    next
  end
  gem name, path: "../#{name}"
end

gem "autotest-suffix", "~> 1.1"
gem "avro", "~> 1.12"
gem "bigdecimal", ">= 3.2", "< 5"
gem "google-style", "~> 1.31.1"
gem "minitest", ">= 5.25", "< 7"
gem "minitest-autotest", "~> 1.1"
gem "minitest-focus", "~> 1.4"
gem "minitest-reporters", "~> 1.7.0", require: false
gem "minitest-rg", "~> 5.3"
gem "pry", "~> 0.15.2"
gem "rake"
gem "redcarpet", "~> 3.6.1"
gem "retriable", "~> 3.1.2"
gem "simplecov", "~> 0.22"
gem "yard", "~> 0.9.37"
gem "yard-doctest", "~> 0.1.17"
