source "https://rubygems.org"

gemspec

gem "google-cloud-core", path: "../google-cloud-core"
gem "google-cloud-env", path: "../google-cloud-env"

gem "minitest-reporters", "~> 1.3.5", require: false
gem "rake", "~> 13.0.0"
