require "bundler/setup"
require "bundler/gem_tasks"

require "rubocop/rake_task"
RuboCop::RakeTask.new

require "rake/testtask"
desc "Run tests."
Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList["test/**/*_test.rb"]
  t.warning = false
end

namespace :test do
  desc "Run tests with coverage."
  task :coverage do
    require "simplecov"
    SimpleCov.start do
      command_name "google-cloud-pubsub"
      track_files "lib/**/*.rb"
      add_filter "test/"
      add_filter "lib/google/pubsub/"
      add_filter "lib/google/cloud/pubsub/v1/"
    end

    Rake::Task[:test].invoke
  end
end

# Acceptance tests
desc "Run the pubsub acceptance tests."
task :acceptance, :project, :keyfile do |_t, args|
  project = args[:project]
  project ||= ENV["PUBSUB_TEST_PROJECT"] || ENV["GCLOUD_TEST_PROJECT"]
  keyfile = args[:keyfile]
  keyfile ||= ENV["PUBSUB_TEST_KEYFILE"] || ENV["GCLOUD_TEST_KEYFILE"]
  if keyfile
    keyfile = File.read keyfile
  else
    keyfile ||= ENV["PUBSUB_TEST_KEYFILE_JSON"] || ENV["GCLOUD_TEST_KEYFILE_JSON"]
  end
  if project.nil? || keyfile.nil?
    raise "You must provide a project and keyfile. e.g. rake acceptance[test123, /path/to/keyfile.json] or " \
          "PUBSUB_TEST_PROJECT=test123 PUBSUB_TEST_KEYFILE=/path/to/keyfile.json rake acceptance"
  end
  # clear any env var already set
  require "google/cloud/pubsub/credentials"
  Google::Cloud::PubSub::Credentials.env_vars.each do |path|
    ENV[path] = nil
  end
  # always overwrite when running tests
  ENV["PUBSUB_PROJECT"] = project
  ENV["PUBSUB_KEYFILE_JSON"] = keyfile

  Rake::Task["acceptance:run"].invoke
end

namespace :acceptance do
  desc "Run acceptance tests with coverage."
  task :coverage, :project, :keyfile do |_t, _args|
    require "simplecov"
    SimpleCov.start do
      command_name "google-cloud-pubsub"
      track_files "lib/**/*.rb"
      add_filter "acceptance/"
    end

    Rake::Task[:acceptance].invoke
  end

  desc "Removes *ALL* topics and subscriptions. Use with caution."
  task :cleanup do |_t, args|
    project = args[:project]
    project ||= ENV["PUBSUB_TEST_PROJECT"] || ENV["GCLOUD_TEST_PROJECT"]
    keyfile = args[:keyfile]
    keyfile ||= ENV["PUBSUB_TEST_KEYFILE"] || ENV["GCLOUD_TEST_KEYFILE"]
    if keyfile
      keyfile = File.read keyfile
    else
      keyfile ||= ENV["PUBSUB_TEST_KEYFILE_JSON"] || ENV["GCLOUD_TEST_KEYFILE_JSON"]
    end
    if project.nil? || keyfile.nil?
      raise "You must provide a project and keyfile. e.g. rake acceptance:cleanup[test123, /path/to/keyfile.json] or " \
            "PUBSUB_TEST_PROJECT=test123 PUBSUB_TEST_KEYFILE=/path/to/keyfile.json rake acceptance:cleanup"
    end
    # clear any env var already set
    require "google/cloud/pubsub/credentials"
    Google::Cloud::PubSub::Credentials.env_vars.each do |path|
      ENV[path] = nil
    end
    # always overwrite when running tests
    ENV["PUBSUB_PROJECT"] = project
    ENV["PUBSUB_KEYFILE_JSON"] = keyfile

    $LOAD_PATH.unshift "lib"
    require "google/cloud/pubsub"
    puts "Cleaning up Pub/Sub topics, subscriptions, and snapshots"
    Google::Cloud.pubsub.topics.all(&:delete)
    Google::Cloud.pubsub.subscriptions.all(&:delete)
    Google::Cloud.pubsub.snapshots.all(&:delete)
  end

  Rake::TestTask.new :run do |t|
    t.libs << "acceptance"
    t.test_files = FileList["acceptance/**/*_test.rb"]
    t.warning = false
  end
end

desc "Run yard-doctest example tests."
# task :doctest do
task :doctest do
  sh "bundle exec yard config load_plugins true && bundle exec yard doctest"
end

task :samples do
  Rake::Task["samples:latest"].invoke
end

namespace :samples do
  task :latest do
    if File.directory? "samples"
      Dir.chdir "samples" do
        Bundler.with_unbundled_env do
          ENV["GOOGLE_CLOUD_SAMPLES_TEST"] = "not_master"
          sh "bundle update"
          sh "bundle exec rake test"
        end
      end
    else
      puts "The google-cloud-pubsub gem has no samples to test."
    end
  end

  task :master do
    if File.directory? "samples"
      Dir.chdir "samples" do
        Bundler.with_unbundled_env do
          ENV["GOOGLE_CLOUD_SAMPLES_TEST"] = "master"
          sh "bundle update"
          sh "bundle exec rake test"
        end
      end
    else
      puts "The google-cloud-pubsub gem has no samples to test."
    end
  end
end

desc "Start an interactive shell."
task :console do
  require "irb"
  require "irb/completion"
  require "pp"

  $LOAD_PATH.unshift "lib"

  require "google-cloud-pubsub"
  def gcloud
    @gcloud ||= Google::Cloud.new
  end

  ARGV.clear
  IRB.start
end

require "yard"
require "yard/rake/yardoc_task"
YARD::Rake::YardocTask.new do |y|
  y.options << "--fail-on-warning"
end

desc "Run the CI build"
task :ci do
  header "BUILDING google-cloud-pubsub"
  header "google-cloud-pubsub rubocop", "*"
  Rake::Task[:rubocop].invoke
  header "google-cloud-pubsub yard", "*"
  Rake::Task[:yard].invoke
  header "google-cloud-pubsub doctest", "*"
  Rake::Task[:doctest].invoke
  header "google-cloud-pubsub test", "*"
  Rake::Task[:test].invoke
end
namespace :ci do
  desc "Run the CI build, with acceptance tests."
  task :acceptance do
    Rake::Task[:ci].invoke
    header "google-cloud-pubsub acceptance", "*"
    Rake::Task[:acceptance].invoke
  end
  task :a do
    # This is a handy shortcut to save typing
    Rake::Task["ci:acceptance"].invoke
  end
end

task default: :test

def header str, token = "#"
  line_length = str.length + 8
  puts ""
  puts token * line_length
  puts "#{token * 3} #{str} #{token * 3}"
  puts token * line_length
  puts ""
end

task :cloudrad do
  ENV["CLOUDRAD_GEM_NAME"] = "google-cloud-pubsub"
  sh "bundle exec yard doc --fail-on-warning --yardopts .yardopts-cloudrad --no-progress"
end
