source "https://rubygems.org"

gemspec

gem "google-cloud-workflows-executions-v1", path: "../google-cloud-workflows-executions-v1"
gem "google-cloud-workflows-executions-v1beta", path: "../google-cloud-workflows-executions-v1beta"
