AllCops:
  TargetRubyVersion: 2.2
  TargetRubyVersion: 2.2
  TargetRubyVersion: 2.2
  TargetRubyVersion: 2.2
  TargetRubyVersion: 2.2
  TargetRubyVersion: 2.2
  Exclude:
    - "google-cloud-phishing_protection.gemspec"
    - "lib/google/**/*"
    - "Rakefile"
    - "test/**/*"
    - "acceptance/**/*"

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
