source "https://rubygems.org"

gemspec

gem "google-cloud-core", path: "../google-cloud-core"
gem "google-cloud-env", path: "../google-cloud-env"
gem "google-cloud-errors", path: "../google-cloud-errors"
gem "google-cloud-phishing_protection-v1beta1", path: "../google-cloud-phishing_protection-v1beta1"

# google-protobuf 3.12.0 requires Ruby 2.5 or later, so pin to 3.11 on older Rubies
gem "google-protobuf", (RUBY_VERSION < "2.5" ? "~> 3.11.4" : "~> 3.12")
