deep-copy-regex:
  - source: /google/cloud/functions/v1/[^/]+-ruby/(.*)
    dest: /owl-bot-staging/google-cloud-functions-v1/$1
docker:
  image: gcr.io/cloud-devrel-public-resources/owlbot-ruby:latest
