source "https://rubygems.org"

gemspec
gem "gapic-common", path: "../gapic-common/"

gem "google-cloud-assured_workloads-v1", path: "../google-cloud-assured_workloads-v1"
gem "google-cloud-assured_workloads-v1beta1", path: "../google-cloud-assured_workloads-v1beta1"
