inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "test/**/*"

Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "*.gemspec"
Naming/FileName:
  Exclude:
    - "lib/google-cloud.rb"
