source "https://rubygems.org"

gemspec

gem "google-cloud-core", path: "../google-cloud-core"
gem "google-cloud-env", path: "../google-cloud-env"
gem "google-cloud-errors", path: "../google-cloud-errors"
gem "google-cloud-monitoring-v3", path: "../google-cloud-monitoring-v3"
gem "google-cloud-monitoring-dashboard-v1", path: "../google-cloud-monitoring-dashboard-v1"
