source "https://rubygems.org"

gemspec

gem "google-cloud-monitoring-v3", path: "../google-cloud-monitoring-v3"
gem "google-cloud-monitoring-dashboard-v1", path: "../google-cloud-monitoring-dashboard-v1"
