# Copyright 2016 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


require "bundler/setup"
require "bundler/gem_tasks"

require "rubocop/rake_task"
RuboCop::RakeTask.new

desc "Run tests."
task :test do
  puts "The google-cloud-monitoring gem does not have tests."
end

namespace :test do
  desc "Run tests with coverage."
  task :coverage do
  end
end

# Acceptance tests
desc "Run the monitoring acceptance tests."
task :acceptance do
  puts "The google-cloud-monitoring gem does not have acceptance tests."
end

namespace :acceptance do
  desc "Run acceptance tests with coverage."
  task :coverage do
  end

  desc "Run acceptance cleanup."
  task :cleanup do
  end
end

desc "Run yard-doctest example tests."
task :doctest do
  puts "The google-cloud-monitoring gem does not have doctest tests."
end

desc "Run rubocop."
task :rubocop do
  puts "The google-cloud-monitoring gem does not use rubocop."
end

require "yard"
require "yard/rake/yardoc_task"
YARD::Rake::YardocTask.new

desc "Generates JSON output from google-cloud-monitoring .yardoc"
task :jsondoc => :yard do
  require "rubygems"
  require "gcloud/jsondoc"

  registry = YARD::Registry.load! ".yardoc"
  generator = Gcloud::Jsondoc::Generator.new registry, "google-cloud-monitoring"
  generator.write_to "jsondoc"
  cp ["docs/toc.json"], "jsondoc", verbose: true
end

desc "Run the CI build"
task :ci do
  header "BUILDING google-cloud-monitoring"
  header "google-cloud-monitoring rubocop", "*"
  sh "bundle exec rake rubocop"
  header "google-cloud-monitoring jsondoc", "*"
  sh "bundle exec rake jsondoc"
  header "google-cloud-monitoring doctest", "*"
  sh "bundle exec rake doctest"
  header "google-cloud-monitoring test", "*"
  sh "bundle exec rake test"
end
namespace :ci do
  desc "Run the CI build, with acceptance tests."
  task :acceptance do
    Rake::Task["ci"].invoke
    header "google-cloud-monitoring acceptance", "*"
    sh "bundle exec rake acceptance -v"
  end
  task :a do
    # This is a handy shortcut to save typing
    Rake::Task["ci:acceptance"].invoke
  end
end

task :default => :test

def header str, token = "#"
  line_length = str.length + 8
  puts ""
  puts token * line_length
  puts "#{token * 3} #{str} #{token * 3}"
  puts token * line_length
  puts ""
end
