# Copyright 2018 Google LLC
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require "bundler/setup"
require "bundler/gem_tasks"

require "rubocop/rake_task"
RuboCop::RakeTask.new

desc "Run tests."
task :test do
  $LOAD_PATH.unshift "lib", "test"
  Dir.glob("test/**/*test.rb")
    .reject { |file| file.include? "smoke_test" }
    .each { |file| require_relative file }
end

namespace :test do
  desc "Runs tests with coverage."
  task :coverage do
    require "simplecov"
    SimpleCov.start do
      command_name "google-cloud-bigtable"
      track_files "lib/**/*.rb"
      add_filter "lib/google/cloud/bigtable/admin/v2/doc"
      add_filter "lib/google/cloud/bigtable/v2/doc"
      add_filter "test/"
    end

    Rake::Task["test"].invoke
  end
end

# Acceptance tests
desc "Run the google-cloud-bigtable acceptance tests."
task :acceptance, :project, :keyfile do |_t, args|
  project = args[:project]
  project ||= ENV["BIGTABLE_TEST_PROJECT"] || ENV["GCLOUD_TEST_PROJECT"]
  keyfile = args[:keyfile]
  keyfile ||= ENV["BIGTABLE_TEST_KEYFILE"] || ENV["GCLOUD_TEST_KEYFILE"]

  unless keyfile
    keyfile ||= ENV["BIGTABLE_TEST_KEYFILE_JSON"] || ENV["GCLOUD_TEST_KEYFILE_JSON"]
  end

  if project.nil? || keyfile.nil?
    raise "You must provide a project and keyfile. e.g. rake acceptance[test123, /path/to/keyfile.json] or BIGTABLE_TEST_PROJECT=test123 BIGTABLE_TEST_KEYFILE=/path/to/keyfile.json rake acceptance"
  end

  # clear any env var already set
  require "google/cloud/bigtable/credentials"
  require "google/cloud/bigtable/admin/credentials"
  (
    Google::Cloud::Bigtable::Credentials::PATH_ENV_VARS +
    Google::Cloud::Bigtable::Credentials::JSON_ENV_VARS +
    Google::Cloud::Bigtable::Admin::Credentials::PATH_ENV_VARS +
    Google::Cloud::Bigtable::Admin::Credentials::JSON_ENV_VARS
  ).each do |path|
    ENV[path] = nil
  end

  # always overwrite when running tests
  ENV["BIGTABLE_PROJECT"] = project
  ENV["BIGTABLE_KEYFILE_JSON"] = keyfile

  Rake::Task["acceptance:run"].invoke
end

namespace :acceptance do
  task :run do
    $LOAD_PATH.unshift "lib", "acceptance"
    Dir.glob("acceptance/**/*_test.rb").each { |file| require_relative file }
  end

  desc "Run acceptance tests with coverage."
  task :coverage, :project, :keyfile do |_t, args|
    require "simplecov"
    SimpleCov.start do
      command_name "google-cloud-bigtable"
      track_files "lib/**/*.rb"
      add_filter "lib/google/cloud/bigtable/admin/v2/doc"
      add_filter "lib/google/cloud/bigtable/v2/doc"
      add_filter "acceptance/"
    end

    Rake::Task["acceptance"].invoke(args[:project], args[:keyfile])
  end

  desc "Run acceptance cleanup."
  task :cleanup do |_t, args|
    project = args[:project]
    project ||= ENV["BIGTABLE_TEST_PROJECT"] || ENV["GCLOUD_TEST_PROJECT"]

    keyfile = args[:keyfile]
    keyfile ||= ENV["BIGTABLE_TEST_KEYFILE"] || ENV["GCLOUD_TEST_KEYFILE"]

    unless keyfile
      keyfile ||= ENV["BIGTABLE_TEST_KEYFILE_JSON"] || ENV["GCLOUD_TEST_KEYFILE_JSON"]
    end

    if project.nil? || keyfile.nil?
      raise "You must provide a project and keyfile. e.g. rake acceptance[test123, /path/to/keyfile.json] or BIGTABLE_TEST_PROJECT=test123 BIGTABLE_TEST_KEYFILE=/path/to/keyfile.json rake acceptance"
    end

    # clear any env var already set
    require "google/cloud/bigtable/credentials"
    require "google/cloud/bigtable/admin/credentials"
    (
      Google::Cloud::Bigtable::Credentials::PATH_ENV_VARS +
      Google::Cloud::Bigtable::Credentials::JSON_ENV_VARS +
      Google::Cloud::Bigtable::Admin::Credentials::PATH_ENV_VARS +
      Google::Cloud::Bigtable::Admin::Credentials::JSON_ENV_VARS
    ).each do |path|
      ENV[path] = nil
    end

    # always overwrite when running tests
    ENV["BIGTABLE_PROJECT"] = project
    ENV["BIGTABLE_KEYFILE_JSON"] = keyfile

    $LOAD_PATH.unshift "lib"
    require "google/cloud/bigtable"
    puts "Cleaning up Bigtable instances and databases."

    gcloud = Google::Cloud.new
    bigtable = gcloud.bigtable
    bigtable.instances.each do |instance|
      begin
        instance.delete
      rescue StandardError => e
        puts "Error while cleaning up #{instance.instance_id} instance.\n\n#{e}"
      end
    end
  end
end

require "yard"
require "yard/rake/yardoc_task"
YARD::Rake::YardocTask.new do |y|
  # y.options << "--fail-on-warning"
end

desc "Run yard-doctest example tests."
task :doctest do
  puts "The google-cloud-bigtable gem does not have doctest tests."
end

desc "Run the CI build"
task :ci do
  header "BUILDING google-cloud-bigtable"
  header "google-cloud-bigtable rubocop", "*"
  Rake::Task["rubocop"].invoke
  header "google-cloud-bigtable yard", "*"
  header "bigtable yard still had warnings", "!"
  Rake::Task["yard"].invoke
  header "google-cloud-bigtable doctest", "*"
  Rake::Task["doctest"].invoke
  header "google-cloud-bigtable test", "*"
  Rake::Task["test"].invoke
end

namespace :ci do
  desc "Run the CI build, with acceptance tests."
  task :acceptance do
    Rake::Task["ci"].invoke
    header "google-cloud-bigtable acceptance", "*"
    Rake::Task["acceptance"].invoke
  end
  task :a do
    # This is a handy shortcut to save typing
    Rake::Task["ci:acceptance"].invoke
  end
end

task :default => :test

def header str, token = "#"
  line_length = str.length + 8
  puts ""
  puts token * line_length
  puts "#{token * 3} #{str} #{token * 3}"
  puts token * line_length
  puts ""
end
