# frozen_string_literal: true

# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Cloud
    module Kms
      module Inventory
        module V1
          # Request message for
          # {::Google::Cloud::Kms::Inventory::V1::KeyDashboardService::Client#list_crypto_keys KeyDashboardService.ListCryptoKeys}.
          # @!attribute [rw] parent
          #   @return [::String]
          #     Required. The Google Cloud project for which to retrieve key metadata, in
          #     the format `projects/*`
          # @!attribute [rw] page_size
          #   @return [::Integer]
          #     Optional. The maximum number of keys to return. The service may return
          #     fewer than this value. If unspecified, at most 1000 keys will be returned.
          #     The maximum value is 1000; values above 1000 will be coerced to 1000.
          # @!attribute [rw] page_token
          #   @return [::String]
          #     Optional. Pass this into a subsequent request in order to receive the next
          #     page of results.
          class ListCryptoKeysRequest
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # Response message for
          # {::Google::Cloud::Kms::Inventory::V1::KeyDashboardService::Client#list_crypto_keys KeyDashboardService.ListCryptoKeys}.
          # @!attribute [rw] crypto_keys
          #   @return [::Array<::Google::Cloud::Kms::V1::CryptoKey>]
          #     The list of {::Google::Cloud::Kms::V1::CryptoKey CryptoKeys}.
          # @!attribute [rw] next_page_token
          #   @return [::String]
          #     The page token returned from the previous response if the next page is
          #     desired.
          class ListCryptoKeysResponse
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end
        end
      end
    end
  end
end
