source "https://rubygems.org"

gemspec

gem "google-style", "~> 1.32.0"
gem "irb", "~> 1.17"
gem "minitest", "~> 6.0.2"
gem "minitest-focus", "~> 1.4"
gem "minitest-mock", "~> 5.27"
gem "minitest-rg", "~> 5.3"
gem "ostruct", "~> 0.5.5"
gem "rake", ">= 13.0"
gem "redcarpet", "~> 3.6"
gem "yard", "~> 0.9"
