source "https://rubygems.org"

gemspec

gem "google-cloud-security_center-v1", path: "../google-cloud-security_center-v1"
gem "google-cloud-security_center-v1p1beta1", path: "../google-cloud-security_center-v1p1beta1"
