# Copyright 2023 Google, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source "https://rubygems.org"

master = ENV["GOOGLE_CLOUD_SAMPLES_TEST"] == "master"

gem "google-cloud-document_ai", path: master ? "../../google-cloud-document_ai" : nil

group :test do
  gem "google-style", ">= 1.26.2", "< 1.28"
  gem "minitest", "~> 5.17"
  gem "minitest-focus", "~> 1.4"
  gem "minitest-rg", "~> 5.2"
  gem "rake"
end
