# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require "bundler/setup"
require "bundler/gem_tasks"

require "rubocop/rake_task"
RuboCop::RakeTask.new

require "rake/testtask"
desc "Run tests."
Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList["test/**/*_test.rb"]
  t.warning = false
end

namespace :test do
  desc "Run tests with coverage."
  task :coverage do
    require "simplecov"
    SimpleCov.start do
      command_name "google-cloud-translate-v2"
      track_files "lib/**/*.rb"
      add_filter "test/"
    end

    Rake::Task[:test].invoke
  end
end

# Acceptance tests
desc "Run the translate acceptance tests."
task :acceptance, :project, :keyfile, :key do |_t, args|
  project = args[:project]
  project ||= ENV["TRANSLATE_TEST_PROJECT"] || ENV["GCLOUD_TEST_PROJECT"]
  keyfile = args[:keyfile]
  keyfile ||= ENV["TRANSLATE_TEST_KEYFILE"] || ENV["GCLOUD_TEST_KEYFILE"]
  if keyfile
    keyfile = File.read keyfile
  else
    keyfile ||= ENV["TRANSLATE_TEST_KEYFILE_JSON"] || ENV["GCLOUD_TEST_KEYFILE_JSON"]
  end
  if project.nil? || keyfile.nil?
    raise "You must provide a project and keyfile. e.g. rake acceptance[test123, /path/to/keyfile.json] or " \
          "TRANSLATE_TEST_PROJECT=test123 TRANSLATE_TEST_KEYFILE=/path/to/keyfile.json rake acceptance"
  end
  key = args[:key]
  key ||= ENV["TRANSLATE_TEST_KEY"] || ENV["GCLOUD_TEST_KEY"]

  # run tests with api key credentials when available
  if key
    puts "running acceptance tests with API key"
    # Rake::Task["acceptance:key"].invoke key
    puts `bundle exec rake acceptance:key[#{key}]`
  end

  # always run tests with service account credentials
  puts "running acceptance tests with service account"

  # clear any env var already set
  require "google/cloud/translate/v2/credentials"
  (Google::Cloud::Translate::V2::Credentials::PATH_ENV_VARS +
   Google::Cloud::Translate::V2::Credentials::JSON_ENV_VARS).each do |path|
    ENV[path] = nil
  end
  # always overwrite when running tests
  ENV["TRANSLATE_PROJECT"] = project
  ENV["TRANSLATE_KEYFILE_JSON"] = keyfile
  ENV["TRANSLATE_KEY"] = nil

  Rake::Task["acceptance:run"].invoke
end

namespace :acceptance do
  task :key, :key do |_t, args|
    key = args[:key]
    key ||= ENV["TRANSLATE_TEST_KEY"] || ENV["GCLOUD_TEST_KEY"]
    raise "unable to run acceptance tests with api key credentials" if key.nil?
    # clear any env var already set
    require "google/cloud/translate/v2/credentials"
    (Google::Cloud::Translate::V2::Credentials::PATH_ENV_VARS +
     Google::Cloud::Translate::V2::Credentials::JSON_ENV_VARS).each do |path|
      ENV[path] = nil
    end
    # always overwrite when running tests
    ENV["TRANSLATE_KEY"] = key

    Rake::Task["acceptance:run"].invoke
  end

  desc "Run acceptance tests with coverage."
  task :coverage, :project, :keyfile do |_t, _args|
    require "simplecov"
    SimpleCov.start do
      command_name "google-cloud-translate-v2"
      track_files "lib/**/*.rb"
      add_filter "acceptance/"
    end

    Rake::Task[:acceptance].invoke
  end

  Rake::TestTask.new :run do |t|
    t.libs << "acceptance"
    t.test_files = FileList["acceptance/**/*_test.rb"]
    t.warning = false
  end
end

desc "Run yard-doctest example tests."
task :doctest do
  sh "bundle exec yard config load_plugins true && bundle exec yard doctest"
end

desc "Start an interactive shell."
task :console do
  require "irb"
  require "irb/completion"
  require "pp"

  $LOAD_PATH.unshift "lib"

  require "google-cloud-translate-v2"
  def gcloud
    @gcloud ||= Google::Cloud.new
  end

  ARGV.clear
  IRB.start
end

require "yard"
require "yard/rake/yardoc_task"
YARD::Rake::YardocTask.new do |y|
  # y.options << "--fail-on-warning"
end

desc "Run the CI build"
task :ci do
  header "BUILDING google-cloud-translate-v2"
  header "google-cloud-translate-v2 rubocop", "*"
  Rake::Task[:rubocop].invoke
  header "google-cloud-translate-v2 yard", "*"
  Rake::Task[:yard].invoke
  header "google-cloud-translate-v2 doctest", "*"
  Rake::Task[:doctest].invoke
  header "google-cloud-translate-v2 test", "*"
  Rake::Task[:test].invoke
end

namespace :ci do
  desc "Run the CI build, with acceptance tests."
  task :acceptance do
    Rake::Task[:ci].invoke
    header "google-cloud-translate-v2 acceptance", "*"
    Rake::Task[:acceptance].invoke
  end
  task :a do
    # This is a handy shortcut to save typing
    Rake::Task["ci:acceptance"].invoke
  end
end

task default: :test

def header str, token = "#"
  line_length = str.length + 8
  puts ""
  puts token * line_length
  puts "#{token * 3} #{str} #{token * 3}"
  puts token * line_length
  puts ""
end
