inherit_gem:
    google-style: google-style.yml

Lint/ShadowingOuterLocalVariable:
    Enabled: false
Metrics/AbcSize:
    Enabled: false
Metrics/BlockLength: 
    Enabled: false
Metrics/CyclomaticComplexity:
    Enabled: false
Metrics/LineLength:
    Exclude:
        - "acceptance/*.rb"
Metrics/MethodLength:
    Enabled: false
Style/IfUnlessModifier:
    Enabled: false
Style/Next:
    Enabled: false
Style/SymbolProc:
    Enabled: false
