inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "acceptance/**/*"
    - "support/**/*"
    - "google-cloud-spanner.gemspec"
    - "Rakefile"
    - "test/**/*"
    - "benchmark/**/*"

Documentation:
  Enabled: false

Layout/AlignHash:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Naming/FileName:
  Exclude:
    - "lib/google-cloud-spanner.rb"
Naming/RescuedExceptionsVariableName:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false
