source "http://rubygems.org"

gemspec

gem "google-cloud-core", path: "../google-cloud-core"
gem "google-cloud-env", path: "../google-cloud-env"
gem "google-cloud-errors", path: "../google-cloud-errors"
gem "google-cloud-spanner-admin-database-v1", path: "../google-cloud-spanner-admin-database-v1"
gem "google-cloud-spanner-admin-instance-v1", path: "../google-cloud-spanner-admin-instance-v1"
gem "google-cloud-spanner-v1", path: "../google-cloud-spanner-v1"

gem "rake"
