# frozen_string_literal: true

# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Cloud
    module OracleDatabase
      module V1
        # Details of the Goldengate Deployment Type resource.
        # @!attribute [rw] name
        #   @return [::String]
        #     Identifier. The name of the Goldengate Deployment Type resource with the
        #     format:
        #     projects/\\{project}/locations/\\{region}/goldengateDeploymentTypes/\\{goldengate_deployment_type}
        # @!attribute [r] deployment_type
        #   @return [::Google::Cloud::OracleDatabase::V1::GoldengateDeploymentType::DeploymentType]
        #     Output only. The deployment type of the Goldengate Deployment Type
        #     resource.
        # @!attribute [r] category
        #   @return [::Google::Cloud::OracleDatabase::V1::GoldengateDeploymentType::DeploymentCategory]
        #     Output only. The category of the Goldengate Deployment Type resource.
        # @!attribute [r] connection_types
        #   @return [::Array<::String>]
        #     Output only. The connection types of the Goldengate Deployment Type
        #     resource.
        # @!attribute [r] display_name
        #   @return [::String]
        #     Output only. The display name of the Goldengate Deployment Type resource.
        # @!attribute [r] ogg_version
        #   @return [::String]
        #     Output only. The Ogg version of the Goldengate Deployment Type resource.
        # @!attribute [r] source_technologies
        #   @return [::Array<::String>]
        #     Output only. The source technologies of the Goldengate Deployment Type
        #     resource.
        # @!attribute [r] supported_capabilities
        #   @return [::Array<::String>]
        #     Output only. The supported capabilities of the Goldengate Deployment Type
        #     resource.
        # @!attribute [r] supported_technologies_url
        #   @return [::String]
        #     Output only. The supported technologies URL of the Goldengate Deployment
        #     Type resource.
        # @!attribute [r] target_technologies
        #   @return [::Array<::String>]
        #     Output only. The target technologies of the Goldengate Deployment Type
        #     resource.
        # @!attribute [r] default_username
        #   @return [::String]
        #     Output only. The default username of the Goldengate Deployment Type
        #     resource.
        class GoldengateDeploymentType
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods

          # The deployment type of the Goldengate Deployment Type resource.
          module DeploymentType
            # Default unspecified value.
            DEPLOYMENT_TYPE_UNSPECIFIED = 0

            # Goldengate Deployment Type category is OGG.
            OGG = 1

            # Goldengate Deployment Type category is DATABASE_ORACLE.
            DATABASE_ORACLE = 2

            # Goldengate Deployment Type category is BIGDATA.
            BIGDATA = 3

            # Goldengate Deployment Type category is DATABASE_MICROSOFT_SQLSERVER.
            DATABASE_MICROSOFT_SQLSERVER = 4

            # Goldengate Deployment Type category is DATABASE_MYSQL.
            DATABASE_MYSQL = 5

            # Goldengate Deployment Type category is DATABASE_POSTGRESQL.
            DATABASE_POSTGRESQL = 6

            # Goldengate Deployment Type category is DATABASE_DB2ZOS.
            DATABASE_DB2ZOS = 7

            # Goldengate Deployment Type category is DATABASE_DB2I.
            DATABASE_DB2I = 8

            # Goldengate Deployment Type category is GGSA.
            GGSA = 9

            # Goldengate Deployment Type category is DATA_TRANSFORMS.
            DATA_TRANSFORMS = 10
          end

          # The category of the Goldengate Deployment Type resource.
          module DeploymentCategory
            # Default unspecified value.
            DEPLOYMENT_CATEGORY_UNSPECIFIED = 0

            # Goldengate Deployment Type category is DATA_REPLICATION_CATEGORY.
            DATA_REPLICATION_CATEGORY = 1

            # Goldengate Deployment Type category is DATA_TRANSFORMS_CATEGORY.
            DATA_TRANSFORMS_CATEGORY = 2
          end
        end

        # Message for getting a GoldengateDeploymentType.
        # @!attribute [rw] name
        #   @return [::String]
        #     Required. The name of the GoldengateDeploymentType to retrieve.
        #     Format:
        #     projects/\\{project}/locations/\\{location}/goldengateDeploymentTypes/\\{goldengate_deployment_type}
        class GetGoldengateDeploymentTypeRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Message for listing GoldengateDeploymentTypes.
        # @!attribute [rw] parent
        #   @return [::String]
        #     Required. The parent resource.
        #     Format: projects/\\{project}/locations/\\{location}
        # @!attribute [rw] page_size
        #   @return [::Integer]
        #     Optional. Requested page size. Server may return fewer items than
        #     requested. If unspecified, server will pick an appropriate default.
        # @!attribute [rw] page_token
        #   @return [::String]
        #     Optional. A token identifying a page of results the server should return.
        # @!attribute [rw] filter
        #   @return [::String]
        #     Optional. An expression for filtering the results of the request. Either
        #     the deployment_type and ogg_version fields must be specified in the format:
        #     `deployment_type="DATABASE_ORACLE"` or `ogg_version="version"`.
        #     Allowed values for deployment_type are: `DATABASE_ORACLE`, `BIGDATA`,
        #     `DATABASE_MICROSOFT_SQLSERVER`, `DATABASE_MYSQL`, `DATABASE_POSTGRESQL`,
        #     `DATABASE_DB2ZOS`, `DATABASE_DB2I`, `GGSA`, `DATA_TRANSFORMS`.
        # @!attribute [rw] order_by
        #   @return [::String]
        #     Optional. Hint for how to order the results
        class ListGoldengateDeploymentTypesRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Message for response to listing GoldengateDeploymentTypes
        # @!attribute [rw] goldengate_deployment_types
        #   @return [::Array<::Google::Cloud::OracleDatabase::V1::GoldengateDeploymentType>]
        #     The list of GoldengateDeploymentType
        # @!attribute [rw] next_page_token
        #   @return [::String]
        #     A token, which can be sent as `page_token` to retrieve the next page.
        #     If this field is omitted, there are no subsequent pages.
        # @!attribute [rw] unreachable
        #   @return [::Array<::String>]
        #     Unordered list. The resource names of locations that could not be reached.
        class ListGoldengateDeploymentTypesResponse
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end
      end
    end
  end
end
