inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "acceptance/**/*"
    - "support/**/*"
    - "benchmark/**/*"
    - "test/**/*"

Style/Documentation:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: false
Metrics/AbcSize:
  Max: 55
Metrics/BlockLength:
  Exclude:
    - "google-cloud-bigquery.gemspec"
    - "Rakefile"
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 14
Metrics/MethodLength:
  Max: 50
Metrics/ModuleLength:
  Exclude:
    - "lib/google/cloud/bigquery/convert.rb"
Metrics/PerceivedComplexity:
  Max: 16
Naming/FileName:
  Exclude:
    - "lib/google-cloud-bigquery.rb"
Naming/MethodParameterName:
  Exclude:
    - "lib/google/cloud/bigquery/external/**/*.rb"
