source "https://rubygems.org"

gemspec

gem "autotest-suffix", "~> 1.1"
gem "google-cloud-core", path: "../google-cloud-core"
gem "google-cloud-data_catalog", "~> 1.2"
gem "google-cloud-errors", path: "../google-cloud-errors"
gem "google-cloud-storage", path: "../google-cloud-storage"
gem "google-style", ">= 1.27.1", "< 1.30.2"
gem "minitest", "~> 5.16"
gem "minitest-autotest", "~> 1.0"
gem "minitest-focus", "~> 1.1"
gem "minitest-reporters", "~> 1.5.0", require: false
gem "minitest-rg", "~> 5.2"
gem "rake"
gem "redcarpet", "~> 3.0"
gem "simplecov", "~> 0.18"
gem "yard", "~> 0.9"
gem "yard-doctest", "~> 0.1.13"
