# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START recaptcha_enterprise_dependencies]
source "https://rubygems.org"

# [END recaptcha_enterprise_dependencies]

if ENV["GOOGLE_CLOUD_SAMPLES_TEST"] == "master"
  gem "google-cloud-recaptcha_enterprise", path: "../../google-cloud-recaptcha_enterprise"
else
  # [START recaptcha_enterprise_dependencies]
  gem "google-cloud-recaptcha_enterprise"
  # [END recaptcha_enterprise_dependencies]
end

group :test do
  gem "google-style", ">= 1.25.1", "< 1.27.1"
  gem "minitest", "~> 5.14"
  gem "minitest-focus", "~> 1.1"
  gem "minitest-hooks", "~> 1.5"
  gem "rake"
  gem "selenium-webdriver", "~> 4.1"
  gem "webrick", "~> 1.7"
end
