# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/dialogflow/v2/environment.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'google/api/field_behavior_pb'
require 'google/api/resource_pb'
require 'google/protobuf/empty_pb'
require 'google/protobuf/field_mask_pb'
require 'google/protobuf/timestamp_pb'
require 'google/api/client_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/cloud/dialogflow/v2/environment.proto", :syntax => :proto3) do
    add_message "google.cloud.dialogflow.v2.Environment" do
      optional :name, :string, 1
      optional :description, :string, 2
      optional :agent_version, :string, 3
      optional :state, :enum, 4, "google.cloud.dialogflow.v2.Environment.State"
      optional :update_time, :message, 5, "google.protobuf.Timestamp"
    end
    add_enum "google.cloud.dialogflow.v2.Environment.State" do
      value :STATE_UNSPECIFIED, 0
      value :STOPPED, 1
      value :LOADING, 2
      value :RUNNING, 3
    end
    add_message "google.cloud.dialogflow.v2.ListEnvironmentsRequest" do
      optional :parent, :string, 1
      optional :page_size, :int32, 2
      optional :page_token, :string, 3
    end
    add_message "google.cloud.dialogflow.v2.ListEnvironmentsResponse" do
      repeated :environments, :message, 1, "google.cloud.dialogflow.v2.Environment"
      optional :next_page_token, :string, 2
    end
  end
end

module Google
  module Cloud
    module Dialogflow
      module V2
        Environment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.dialogflow.v2.Environment").msgclass
        Environment::State = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.dialogflow.v2.Environment.State").enummodule
        ListEnvironmentsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.dialogflow.v2.ListEnvironmentsRequest").msgclass
        ListEnvironmentsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.dialogflow.v2.ListEnvironmentsResponse").msgclass
      end
    end
  end
end
