source "https://rubygems.org"

gemspec
gem "gapic-common", path: "../gapic-common/"

gem "google-cloud-security-private_ca-v1", path: "../google-cloud-security-private_ca-v1"
gem "google-cloud-security-private_ca-v1beta1", path: "../google-cloud-security-private_ca-v1beta1"
