# Copyright 2020 Google, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START asset_dependencies]
source "https://rubygems.org"

# [END asset_dependencies]

if ENV["GOOGLE_CLOUD_SAMPLES_TEST"] == "master"
  gem "google-cloud-asset", path: "../../google-cloud-asset"
  gem "google-cloud-asset-v1", path: "../../google-cloud-asset-v1"
  gem "google-cloud-bigquery", group: :test, path: "../../google-cloud-bigquery"
  gem "google-cloud-pubsub", group: :test, path: "../../google-cloud-pubsub"
  gem "google-cloud-storage", group: :test, path: "../../google-cloud-storage"
else
  # [START asset_dependencies]
  gem "google-cloud-asset"
  # [END asset_dependencies]
  gem "google-cloud-bigquery", group: :test
  gem "google-cloud-pubsub", group: :test
  gem "google-cloud-storage", group: :test
end

group :test do
  gem "minitest", "~> 5.14"
  gem "minitest-focus"
  gem "rake"
end
