# frozen_string_literal: true

# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!

require "google/cloud/document_ai/v1beta3/document_processor_service/rest"
require "google/cloud/document_ai/v1beta3/document_service/rest"
require "google/cloud/document_ai/v1beta3/bindings_override"
require "google/cloud/document_ai/v1beta3/version"

module Google
  module Cloud
    module DocumentAI
      ##
      # To load just the REST part of this package, including all its services, and instantiate a REST client:
      #
      # @example
      #
      #     require "google/cloud/document_ai/v1beta3/rest"
      #     client = ::Google::Cloud::DocumentAI::V1beta3::DocumentProcessorService::Rest::Client.new
      #
      module V1beta3
      end
    end
  end
end
