source "https://rubygems.org"

gemspec
gem "gapic-common", path: "../gapic-common/"

gem "google-cloud-dataproc-v1", path: "../google-cloud-dataproc-v1"
gem "google-cloud-dataproc-v1beta2", path: "../google-cloud-dataproc-v1beta2"
