# frozen_string_literal: true

source "https://rubygems.org"

gem "google-cloud-bigtable", path: "../../"
gem "grpc", "~> 1.65"
gem "grpc-tools", "~> 1.65"
gem "googleapis-common-protos", "~> 1.6"
gem "googleapis-common-protos-types", "~> 1.15"
