source "https://rubygems.org"

gemspec

gem "rake", "~> 11.0"
gem "google-cloud", path: "../google-cloud"
gem "google-cloud-core", path: "../google-cloud-core"
gem "google-cloud-env", path: "../google-cloud-env"
gem "google-cloud-bigquery", path: "../google-cloud-bigquery"
gem "google-cloud-datastore", path: "../google-cloud-datastore"
gem "google-cloud-dns", path: "../google-cloud-dns"
gem "google-cloud-error_reporting", path: "../google-cloud-error_reporting"
gem "google-cloud-language", path: "../google-cloud-language"
gem "google-cloud-logging", path: "../google-cloud-logging"
gem "google-cloud-monitoring", path: "../google-cloud-monitoring"
gem "google-cloud-pubsub", path: "../google-cloud-pubsub"
gem "google-cloud-resource_manager", path: "../google-cloud-resource_manager"
gem "google-cloud-spanner", path: "../google-cloud-spanner"
gem "google-cloud-speech", path: "../google-cloud-speech"
gem "google-cloud-storage", path: "../google-cloud-storage"
gem "google-cloud-trace", path: "../google-cloud-trace"
gem "google-cloud-translate", path: "../google-cloud-translate"
gem "google-cloud-vision", path: "../google-cloud-vision"
gem "google-cloud-video_intelligence",
    path: "../google-cloud-video_intelligence"
gem "stackdriver-core", path: "../stackdriver-core"

gem "gcloud-jsondoc",
    git: "https://github.com/GoogleCloudPlatform/google-cloud-ruby.git",
    branch: "gcloud-jsondoc"

# WORKAROUND: builds are having problems since the release of 3.0.0
# pin to the last known good version
gem "public_suffix", "~> 2.0"

# TEMP: rainbow (a dependency of rubocop) version 2.2 seems to have a problem,
# so pinning to 2.1 for now.
gem "rainbow", "~> 2.1.0"
