source "http://rubygems.org"

gemspec

gem "rake"
gem "google-cloud", path: "../google-cloud"
gem "google-cloud-core", path: "../google-cloud-core"
gem "google-cloud-bigquery", path: "../google-cloud-bigquery"
gem "google-cloud-datastore", path: "../google-cloud-datastore"
gem "google-cloud-dns", path: "../google-cloud-dns"
gem "google-cloud-logging", path: "../google-cloud-logging"
gem "google-cloud-pubsub", path: "../google-cloud-pubsub"
gem "google-cloud-resource_manager", path: "../google-cloud-resource_manager"
gem "google-cloud-storage", path: "../google-cloud-storage"
gem "google-cloud-translate", path: "../google-cloud-translate"
gem "google-cloud-vision", path: "../google-cloud-vision"

gem "gcloud-jsondoc",
    git: "https://github.com/GoogleCloudPlatform/google-cloud-ruby.git",
    branch: "gcloud-jsondoc"
