require "bundler/gem_tasks"

require "rake/testtask"
Rake::TestTask.new(:test) do |test|
  test.warning = true
  test.libs << "test"
  test.pattern = "test/**/*_test.rb"
end

task :console do
  require "irb"
  require "irb/completion"
  require "pp"

  $LOAD_PATH.unshift "lib"

  require "gcloud"
  def gcloud; @gcloud ||= Gcloud.new; end

  ARGV.clear
  IRB.start
end

task :default => :test
