# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START datastore_admin_dependencies]
source "https://rubygems.org"

# [END datastore_admin_dependencies]

if ENV["GOOGLE_CLOUD_SAMPLES_TEST"] == "master"
  gem "google-cloud-datastore-admin-v1", path: "../../google-cloud-datastore-admin-v1"
else
  # [START datastore_admin_dependencies]
  gem "google-cloud-datastore-admin-v1"
  # [END datastore_admin_dependencies]
end

group :test do
  gem "google-cloud-storage"
  gem "google-style", ">= 1.25.1", "< 1.27.2"
  gem "minitest", "~> 5.14"
  gem "minitest-focus", "~> 1.1"
  gem "minitest-hooks", "~> 1.5"
  gem "rake"
end
