source "https://rubygems.org"

gemspec

gem "google-cloud-core", path: "../google-cloud-core"
gem "google-cloud-env", path: "../google-cloud-env"
gem "google-cloud-logging", path: "../google-cloud-logging"
gem "stackdriver-core", path: "../stackdriver-core"

gem "rake", "~> 12.3"
