require "bundler/setup"
require "bundler/gem_tasks"
require "fileutils"

require "rubocop/rake_task"
RuboCop::RakeTask.new

require "rake/extensiontask"
spec = Gem::Specification.load("google-cloud-debugger.gemspec")
ext_name = "google/cloud/debugger/debugger_c"
Rake::ExtensionTask.new(ext_name, spec)

namespace :compile do
  desc "Cleanup compilation files"
  task :cleanup do
    Dir.glob "lib/google/cloud/debugger/debugger_c.*" do |f|
      puts "remove #{f}"
      File.delete f
    end

    puts "remove directory ./tmp"
    FileUtils.remove_dir "tmp", true
  end
end

desc "Clean up compilation files and compile again"
task :recompile do
  Rake::Task["compile:cleanup"].invoke
  Rake::Task["compile"].invoke
end

desc "Run tests."
task :test => :compile do
  $LOAD_PATH.unshift "lib", "test"
  Dir.glob("test/**/*_test.rb").each { |file| require_relative file }
end

namespace :test do
  desc "Run tests with coverage."
  task :coverage do
    require "simplecov"
    SimpleCov.start do
      command_name "google-cloud-debugger"
      track_files "lib/**/*.rb"
      add_filter "test/"
    end

    Rake::Task["test"].invoke
  end
end

# Acceptance tests
desc "Runs the trace acceptance tests."
task :acceptance, :project, :keyfile do |t, args|
  project = args[:project]
  project ||= ENV["DEBUGGER_TEST_PROJECT"] || ENV["GCLOUD_TEST_PROJECT"]
  keyfile = args[:keyfile]
  keyfile ||= ENV["DEBUGGER_TEST_KEYFILE"] || ENV["GCLOUD_TEST_KEYFILE"]
  if keyfile
    keyfile = File.read keyfile
  else
    keyfile ||= ENV["DEBUGGER_TEST_KEYFILE_JSON"] || ENV["GCLOUD_TEST_KEYFILE_JSON"]
  end
  if project.nil? || keyfile.nil?
    fail "You must provide a project and keyfile. e.g. rake acceptance[test123,/path/to/keyfile.json] or DEBUGGER_TEST_PROJECT=test123 DEBUGGER_TEST_KEYFILE=/path/to/keyfile.json rake acceptance"
  end
  # clear any env var already set
  require "google/cloud/debugger/credentials"
  (Google::Cloud::Debugger::Credentials::PATH_ENV_VARS +
   Google::Cloud::Debugger::Credentials::JSON_ENV_VARS).each do |path|
    ENV[path] = nil
  end
  require "google/cloud/logging/credentials"
  (Google::Cloud::Logging::Credentials::PATH_ENV_VARS +
   Google::Cloud::Logging::Credentials::JSON_ENV_VARS).each do |path|
    ENV[path] = nil
  end
  # always overwrite when running tests
  ENV["DEBUGGER_PROJECT"] = project
  ENV["DEBUGGER_KEYFILE_JSON"] = keyfile
  ENV["LOGGING_PROJECT"] = project
  ENV["LOGGING_KEYFILE_JSON"] = keyfile

  Rake::Task["acceptance:run"].invoke
end

namespace :acceptance do
  desc "Runs acceptance tests with coverage."
  task :coverage, :project, :keyfile do |t, args|
    require "simplecov"
    SimpleCov.start do
      command_name "google-cloud-debugger"
      track_files "lib/**/*.rb"
      add_filter "acceptance/"
    end

    Rake::Task["acceptance"].invoke
  end

  task :run do
    $LOAD_PATH.unshift "lib", "acceptance"
    Dir.glob("acceptance/debugger/**/*_test.rb").each { |file| require_relative file }
  end
end

namespace :integration do
  desc "Run integration tests against GAE"
  task :gae, [:project_uri] => :recompile do |t, args|
    fail "You must provide a project_uri. e.g. rake " \
      "integration:gae[http://my-project.appspot-preview.com]" if args[:project_uri].nil?

    ENV["TEST_GOOGLE_CLOUD_PROJECT_URI"] = args[:project_uri]

    $LOAD_PATH.unshift "lib", "integration"
    Dir.glob("integration/*_test.rb").each { |file| require_relative file }
    Dir.glob("integration/gae/**/*_test.rb").each { |file| require_relative file }
  end

  desc "Run integration tests against GKE"
  task :gke, [:pod_name] => :recompile do |t, args|
    fail "You must provide the GKE pod name. e.g. " \
      "rake integration:gke[google-cloud-ruby-test]" if args[:pod_name].nil?

    ENV["TEST_GKE_POD_NAME"] = args[:pod_name]

    $LOAD_PATH.unshift "lib", "integration"
    Dir.glob("integration/*_test.rb").each { |file| require_relative file }
    Dir.glob("integration/gke/**/*_test.rb").each { |file| require_relative file }
  end
end

desc "Run yard-doctest example tests."
task doctest: :yard do
  sh "bundle exec yard config -a autoload_plugins yard-doctest"
  sh "bundle exec yard doctest"
end

desc "Start an interactive shell."
task :console => :compile do
  require "irb"
  require "irb/completion"
  require "pp"

  $LOAD_PATH.unshift "lib"

  require "google-cloud-debugger"
  def gcloud; @gcloud ||= Google::Cloud.new; end

  ARGV.clear
  IRB.start
end

require "yard"
require "yard/rake/yardoc_task"
YARD::Rake::YardocTask.new

desc "Generates JSON output from google-cloud-debugger .yardoc"
task :jsondoc => [:compile, :yard] do
  require "rubygems"
  require "gcloud/jsondoc"

  registry = YARD::Registry.load! ".yardoc"
  generator = Gcloud::Jsondoc::Generator.new registry, "google-cloud-debugger"
  rm_rf "jsondoc", verbose: true
  generator.write_to "jsondoc"
  cp ["docs/authentication.md", "docs/instrumentation.md", "docs/toc.json"], "jsondoc", verbose: true
end

desc "Run the CI build"
task :ci do
  header "BUILDING google-cloud-debugger"
  header "google-cloud-debugger rubocop", "*"
  sh "bundle exec rake rubocop"
  header "google-cloud-debugger jsondoc", "*"
  sh "bundle exec rake jsondoc"
  header "google-cloud-debugger doctest", "*"
  sh "bundle exec rake doctest"
  header "google-cloud-debugger test", "*"
  sh "bundle exec rake test"
end
namespace :ci do
  desc "Run the CI build, with acceptance tests."
  task :acceptance do
    Rake::Task["ci"].invoke
    header "google-cloud-debugger acceptance", "*"
    sh "bundle exec rake acceptance -v"
  end
  task :a do
    # This is a handy shortcut to save typing
    Rake::Task["ci:acceptance"].invoke
  end
end

task :default => :test

def header str, token = "#"
  line_length = str.length + 8
  puts ""
  puts token * line_length
  puts "#{token * 3} #{str} #{token * 3}"
  puts token * line_length
  puts ""
end
