source "https://rubygems.org"

gemspec

gem "google-api-client", "~> 0.36"
gem "google-gax", "~> 1.8"

gem "rake", "~> 12.3"

# Pin minitest to 5.11.x to avoid warnings emitted by 5.12.
# See https://github.com/googleapis/google-cloud-ruby/issues/4110
gem "minitest", "~> 5.11.3"
