source "https://rubygems.org"

gemspec

gem "google-cloud-container_analysis-v1", path: "../google-cloud-container_analysis-v1"
gem "grafeas-v1", path: "../grafeas-v1"

# google-protobuf 3.12.0 requires Ruby 2.5 or later, so pin to 3.11 on older Rubies
gem "google-protobuf", (RUBY_VERSION < "2.5" ? "~> 3.11.4" : "~> 3.12")
