source "https://rubygems.org"

gemspec

gem "grafeas-client", path: "../grafeas-client"
gem "rake", "~> 12.0"

# Pin minitest to 5.11.x to avoid warnings emitted by 5.12.
# See https://github.com/googleapis/google-cloud-ruby/issues/4110
gem "minitest", "~> 5.11.3"
