AllCops:
  Exclude:
    - "google-cloud-env.gemspec"
    - "Rakefile"
    - "test/**/*"

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 25
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Metrics/ParameterLists:
  Enabled: false
Layout/EmptyLines: # for the extra line between copyright and code
  Enabled: false
Naming/FileName:
  Exclude:
    - "lib/google-cloud-env.rb"
