# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source "https://rubygems.org"

if ENV["GOOGLE_CLOUD_SAMPLES_TEST"] == "master"
  gem "google-cloud-security_center", path: "../../google-cloud-security_center"
  gem "google-cloud-security_center-v1", path: "../../google-cloud-security_center-v1"
  gem "google-cloud-security_center-v1p1beta1", path: "../../google-cloud-security_center-v1p1beta1"
else
  gem "google-cloud-security_center"
end

group :test do
  gem "minitest", "~> 5.14"
  gem "rake", ">= 12.0"
end
