name: Bump-Version

permissions:
  contents: read
on:
  workflow_dispatch:
    inputs:
      gems:
        description: "Gems to bump (required)"
        required: true
      version:
        description: "Version to bump to (required)"
        required: true
      args:
        description: "Extra command line arguments"
        required: false

jobs:
  bump-version:
    if: ${{ github.repository == 'googleapis/google-cloud-ruby' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Install Ruby 3.3
        uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
        with:
          ruby-version: "3.3"
      - name: Install tools
        run: |
          gem install --no-document toys
      - name: execute
        run: |
          toys bump-version -v --fork \
            --version "${GITHUB_EVENT_INPUTS_VERSION}" \
            ${GITHUB_EVENT_INPUTS_ARGS} -- \
            ${GITHUB_EVENT_INPUTS_GEMS}
        env:
          GITHUB_EVENT_INPUTS_VERSION: ${{ github.event.inputs.version }}
          GITHUB_EVENT_INPUTS_ARGS: ${{ github.event.inputs.args }}
          GITHUB_EVENT_INPUTS_GEMS: ${{ github.event.inputs.gems }}
