name: OwlBot Migration

on:
  workflow_dispatch:
    inputs:
      gems:
        description: "List of gems, or --all for all gems"
        required: true

jobs:
  OwlBot-Migrate:
    if: ${{ github.repository == 'googleapis/google-cloud-ruby' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install Ruby 3.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.0"
    - name: Install tools
      run: |
        git config --global user.email "70984784+yoshi-code-bot@users.noreply.github.com"
        git config --global user.name "Yoshi Code Bot"
        gem install --no-document toys
    - name: OwlBot Migrate
      run: |
        toys owlbot-migrate -v --pull --remote=origin ${{ github.event.inputs.gems }}
