name: Release-Please Now
on:
  schedule:
    - cron: '21 10 * * 1-4'
  workflow_dispatch:
    inputs:
      args:
        description: "Extra command line arguments."
        required: false

jobs:
  add-release-please-label:
    if: ${{ github.repository == 'googleapis/google-cloud-ruby' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELEASE_PLEASE_DISABLE: ${{ secrets.RELEASE_PLEASE_DISABLE }}
    permissions:
      contents: read
      packages: read
      pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - name: Install Ruby 3.3
        uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
        with:
          ruby-version: "3.3"
      - name: Install tools
        run: |
          gem install --no-document toys
      - name: execute
        run: |
          toys release label-please -v \
            --github-event-name=${{ github.event_name }} \
            ${GITHUB_EVENT_INPUTS_ARGS}
        env:
          GITHUB_EVENT_INPUTS_ARGS: ${{ github.event.inputs.args }}
