name: Release-Please Now
on:
  schedule:
    - cron: '21 10 * * *'
  workflow_dispatch:
    inputs:
      args:
        description: "Extra command line arguments."
        required: false

jobs:
  add-release-please-label:
    if: ${{ github.repository == 'googleapis/google-cloud-ruby' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELEASE_PLEASE_DISABLE: ${{ secrets.RELEASE_PLEASE_DISABLE }}
    permissions:
      contents: read
      packages: read
      pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false
      - name: Install Ruby 3.3
        uses: ruby/setup-ruby@0dafeac902942906541bc140009cdbf32665b601 # v1.315.0
        with:
          ruby-version: "3.3"
      - name: Install tools
        run: |
          gem install --no-document toys
      - name: execute
        run: |
          toys release label-please -v \
            --github-event-name=${{ github.event_name }} \
            ${GITHUB_EVENT_INPUTS_ARGS}
        env:
          GITHUB_EVENT_INPUTS_ARGS: ${{ github.event.inputs.args }}
