permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - 'google-cloud-storage/**'
  pull_request:
    paths:
      - 'google-cloud-storage/**'
name: Run Storage retry conformance tests against service emulator
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: google-cloud-storage

    services:
      emulator:
        image: gcr.io/cloud-devrel-public-resources/storage-testbench@sha256:600fa5c3cfc8be26435c38591cc094fb4ef648f760ffabf77f93237b1ebee027 # v0.63.0
        ports:
          - 9000:9000

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
        with:
          ruby-version: '3.3'
      - run: ruby --version
      - run: gem install toys
      - run: bundle install
      - run: toys conformance
        env:
          STORAGE_EMULATOR_HOST: localhost:9000
