name: Tombstone a Library

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      gem:
        description: "gem name to tombstone"
        required: true
      flags:
        description: "Extra flags to pass to toys tombstone-library"
        required: false

jobs:
  TombstoneLibrary:
    if: ${{ github.repository == 'googleapis/google-cloud-ruby' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      with:
        persist-credentials: false
    - name: Install Ruby 3.4
      uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
      with:
        ruby-version: "3.4"
    - name: Install tools
      run: |
        gem install --no-document toys
    - name: Tombstone-library
      run: |
        toys tombstone-library -v --fork ${GITHUB_EVENT_INPUTS_FLAGS} ${GITHUB_EVENT_INPUTS_GEM}
      env:
        GITHUB_EVENT_INPUTS_FLAGS: ${{ github.event.inputs.flags }}
        GITHUB_EVENT_INPUTS_GEM: ${{ github.event.inputs.gem }}
