AllCops:
  Exclude:
    - "google-cloud-video_intelligence.gemspec"
    - "lib/google/cloud/video_intelligence.rb"
    - "lib/google/cloud/video_intelligence/**/*"
    - "lib/google/cloud/videointelligence/**/*"
    - "Rakefile"
    - "test/**/*"
    - "acceptance/google/cloud/video_intelligence/v1/video_intelligence_service_smoke_test.rb"

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/NumericLiterals:
  Enabled: false
Style/SpaceAroundOperators:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/EmptyLines:
  Enabled: false
Style/EmptyElse:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 25
Metrics/MethodLength:
  Max: 20
Metrics/ParameterLists:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
Style/FileName:
  Enabled: false # for lib/google-cloud-video_intelligence.rb file
Lint/HandleExceptions:
  Enabled: false
