source "https://rubygems.org"

gemspec

gem "google-cloud-video_intelligence-v1", path: "../google-cloud-video_intelligence-v1"
gem "google-cloud-video_intelligence-v1beta2", path: "../google-cloud-video_intelligence-v1beta2"
gem "google-cloud-video_intelligence-v1p1beta1", path: "../google-cloud-video_intelligence-v1p1beta1"
gem "google-cloud-video_intelligence-v1p2beta1", path: "../google-cloud-video_intelligence-v1p2beta1"

# google-protobuf 3.12.0 requires Ruby 2.5 or later, so pin to 3.11 on older Rubies
gem "google-protobuf", (RUBY_VERSION < "2.5" ? "~> 3.11.4" : "~> 3.12")
